//! The coverage deck set (decks/coverage/) contains every castable card the
//! engine implements — so a fuzz campaign over those decks can, in
//! principle, reach every card, and a card added to the registry without a
//! deck slot fails the suite instead of silently going unfuzzed.
//!
//! The decks were generated by scripts/make_coverage_decks.py; regenerate
//! (or just add the new card to a fitting deck by hand) when this fails.

use std::collections::BTreeSet;
use std::path::Path;

use mtg_engine::cards::CardRegistry;

fn coverage_deck_entries() -> Vec<(String, String)> {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../decks/coverage");
    let mut entries = Vec::new();
    let mut decks = 0;
    for file in std::fs::read_dir(&dir).expect("decks/coverage exists") {
        let path = file.expect("readable dir entry").path();
        if path.extension().and_then(|e| e.to_str()) != Some("txt") {
            continue;
        }
        decks += 1;
        let deck = path.file_stem().unwrap().to_string_lossy().into_owned();
        let text = std::fs::read_to_string(&path).expect("readable deck file");
        for line in text.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let (count, name) = line.split_once(' ')
                .unwrap_or_else(|| panic!("{deck}: malformed line {line:?}"));
            count.parse::<u32>()
                .unwrap_or_else(|_| panic!("{deck}: bad count in {line:?}"));
            entries.push((deck.clone(), name.trim().to_string()));
        }
    }
    assert!(decks >= 10, "expected the ten coverage decks, found {decks}");
    entries
}

#[test]
fn the_coverage_decks_contain_every_implemented_card() {
    let registry = CardRegistry::with_all_cards();
    let entries = coverage_deck_entries();
    let in_decks: BTreeSet<&str> = entries.iter().map(|(_, n)| n.as_str()).collect();

    let missing: Vec<&str> = registry.all_names().into_iter()
        .filter(|n| !in_decks.contains(n))
        .collect();
    assert!(missing.is_empty(),
        "{} card(s) in the registry appear in no coverage deck — add each to \
         a fitting deck in decks/coverage/ (or regenerate with \
         scripts/make_coverage_decks.py):\n  {}",
        missing.len(), missing.join("\n  "));

    let unknown: Vec<String> = entries.iter()
        .filter(|(_, n)| registry.get_id_by_name(n).is_none())
        .map(|(d, n)| format!("{d}: {n}"))
        .collect();
    assert!(unknown.is_empty(),
        "coverage deck entries name cards the registry does not know:\n  {}",
        unknown.join("\n  "));
}
