//! A pump spell is a snapshot. A static anthem is not.
//!
//! CR 611.2c: "If a continuous effect generated by the resolution of a spell or
//! ability modifies the characteristics ... of any objects, the set of objects
//! it affects is determined when that spell or ability resolves. After that,
//! the set of objects won't change. (Note that this works differently than a
//! continuous effect from a static ability.) An object that comes under a
//! player's control after a spell or ability resolves won't be affected by that
//! effect."
//!
//! That parenthetical is the whole file. Glorious Anthem is a permanent's
//! static ability and pumps creatures as they arrive; Overrun is a spell and
//! does not. "Creatures you control get +2/+0 until end of turn" printed on an
//! instant is Overrun, not Glorious Anthem.
//!
//! This file previously asserted the reverse, in as many words — "a creature
//! that arrives after the anthem resolved is still a creature you control, so
//! it gets the bonus too" — and four ISD cards had been implemented to match,
//! as a live `ModifyPTAll` filter re-evaluated every time P/T was computed. The
//! tests came first and the code was made to fit them, which is why nothing
//! caught it.

mod common;
use common::*;

use mtg_engine::cards::CardRegistry;
use mtg_engine::state::GameState;
use mtg_engine::types::*;

/// Put `name` on the stack and resolve it, with whatever is already on the
/// battlefield in place.
fn resolve_anthem(state: &mut GameState, reg: &CardRegistry, name: &str) {
    let card_id = reg.get_id_by_name(name).unwrap_or_else(|| panic!("unknown card {name}"));
    let spell = state.create_object(card_id, P0, Zone::Stack, None, None);
    state.get_object_mut(spell).unwrap().name = name.into();
    reg.get(card_id).unwrap().on_resolve(state, spell, &[], reg);
}

/// Every "until end of turn" anthem in the set, in both directions: the
/// creature that was on the battlefield when it resolved gets the bonus, and
/// one that arrives a moment later does not.
///
/// The second half is the one that matters. Resolving the spell onto an empty
/// battlefield and then playing a creature is the cleanest statement of
/// CR 611.2c there is — the affected set was empty, so it stays empty.
#[test]
fn an_until_end_of_turn_anthem_is_fixed_at_resolution() {
    // (anthem, a creature it names, that creature's printed power, buffed power)
    const CASES: &[(&str, &str, i32, i32)] = &[
        ("Rally the Peasants", "Grizzly Bears", 2, 4),
        ("Vampiric Fury", "Stromkirk Noble", 1, 3),
    ];

    for &(anthem, creature, printed, buffed) in CASES {
        let reg = registry();

        // Present when it resolves: buffed.
        let mut state = game_at_step(Step::PrecombatMain, P0);
        let early = named_permanent(&mut state, &reg, creature, P0);
        assert_eq!(state.effective_power(early, &reg), Some(printed),
            "{anthem}: test premise — {creature} is printed {printed} power");
        resolve_anthem(&mut state, &reg, anthem);
        assert_eq!(state.effective_power(early, &reg), Some(buffed),
            "{anthem} reaches {creature}, which was there when it resolved");

        // Arrives afterwards: untouched.
        let late = named_permanent(&mut state, &reg, creature, P0);
        assert_eq!(state.effective_power(late, &reg), Some(printed),
            "{anthem} does not reach {creature}, which entered after it \
             resolved — the affected set was fixed then (CR 611.2c)");
    }
}

/// The filtered anthem reaches only what it names, among the creatures that
/// were there when it resolved.
#[test]
fn vampiric_fury_reaches_vampires_and_nothing_else() {
    let reg = registry();
    let mut state = game_at_step(Step::PrecombatMain, P0);

    let vampire = named_permanent(&mut state, &reg, "Stromkirk Noble", P0);
    let not_a_vampire = named_permanent(&mut state, &reg, "Grizzly Bears", P0);
    let their_vampire = named_permanent(&mut state, &reg, "Stromkirk Noble", P1);

    resolve_anthem(&mut state, &reg, "Vampiric Fury");

    assert_eq!(state.effective_power(vampire, &reg), Some(3), "your Vampire");
    assert!(state.has_keyword(vampire, Keyword::FirstStrike, &reg),
        "and it gains first strike too");
    assert_eq!(state.effective_power(not_a_vampire, &reg), Some(2), "a non-Vampire");
    assert_eq!(state.effective_power(their_vampire, &reg), Some(1),
        "an opponent's Vampire");

    // A Vampire cast afterwards is not in the set, filter or no filter.
    let late_vampire = named_permanent(&mut state, &reg, "Stromkirk Noble", P0);
    assert_eq!(state.effective_power(late_vampire, &reg), Some(1),
        "a Vampire that entered after it resolved gets nothing (CR 611.2c)");
}

/// "Creatures you control gain protection from non-Human creatures until end of
/// turn" — the same rule for a granted keyword rather than a P/T change.
#[test]
fn spare_from_evil_protects_only_what_was_there() {
    let reg = registry();
    let mut state = game_at_step(Step::PrecombatMain, P0);

    let present = ready_creature(&mut state, P0, 2, 2);
    let non_human = named_permanent(&mut state, &reg, "Grizzly Bears", P1);
    let human = named_permanent(&mut state, &reg, "Avacyn's Pilgrim", P1);

    resolve_anthem(&mut state, &reg, "Spare from Evil");

    assert!(state.has_protection_from(present, non_human, &reg),
        "a creature that was out when it resolved gains the protection");
    assert!(!state.has_protection_from(present, human, &reg),
        "protection from *non-Human* creatures, so a Human is not covered");

    let newcomer = ready_creature(&mut state, P0, 2, 2);
    assert!(!state.has_protection_from(newcomer, non_human, &reg),
        "a creature entering afterwards is not in the affected set (CR 611.2c)");
}

/// Selfless Cathar's anthem comes from an activated ability that sacrifices it
/// ("{1}{W}, Sacrifice this creature: Creatures you control get +1/+1 until end
/// of turn"), so it is applied from the graveyard. CR 611.2c covers abilities
/// as well as spells, so it is fixed at resolution just the same.
#[test]
fn selfless_cathars_anthem_is_fixed_at_resolution() {
    let reg = registry();
    let mut state = game_at_step(Step::PrecombatMain, P0);

    let cathar = named_permanent(&mut state, &reg, "Selfless Cathar", P0);
    let already_there = ready_creature(&mut state, P0, 2, 2);

    // The engine sacrifices the Cathar before the ability's handler runs.
    state.move_object(cathar, Zone::Graveyard, &reg);
    reg.get(state.get_object(cathar).unwrap().card_id).unwrap()
        .on_activate_ability(&mut state, cathar, 0, &[], &reg);

    assert_eq!(state.effective_power(already_there, &reg), Some(3),
        "the creature that was already out gets +1/+1");

    let newcomer = ready_creature(&mut state, P0, 2, 2);
    assert_eq!(state.effective_power(newcomer, &reg), Some(2),
        "one that arrives afterwards does not (CR 611.2c)");
}

/// The other direction. Instigator Gang's "Attacking creatures you control get
/// +1/+0" is a *static* ability, so it stops the moment the Gang leaves — it is
/// not an until-end-of-turn effect that outlives its source.
#[test]
fn a_static_anthem_stops_when_its_source_leaves() {
    use mtg_engine::state::TemporaryEffect;

    let reg = registry();
    let mut state = game_at_step(Step::DeclareAttackers, P0);

    let gang = named_permanent(&mut state, &reg, "Instigator Gang", P0);
    let attacker = ready_creature(&mut state, P0, 2, 2);

    state.until_end_of_turn.push(TemporaryEffect::ModifyPTWhileSourceInPlay {
        target: attacker,
        source: gang,
        power_mod: 1,
        toughness_mod: 0,
    });
    assert_eq!(state.effective_power(attacker, &reg), Some(3),
        "test precondition: with the Gang out, the attacker is 3/2");

    state.move_object(gang, Zone::Graveyard, &reg);

    assert_eq!(state.effective_power(attacker, &reg), Some(2),
        "the Gang is gone, so its static ability is gone — the +1/+0 must not \
         linger to end of turn the way a spell's anthem would");
}
