use std::collections::HashMap;

use serde::{Serialize, Deserialize};

use crate::ids::{ObjectId, PlayerId, CardId};
use crate::types::{Zone, Step, ManaPool};

/// The complete, immutable game state. Clone to produce new states.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GameState {
    /// All game objects keyed by their unique ID.
    pub objects: HashMap<ObjectId, GameObject>,
    /// Monotonic counter for generating unique ObjectIds.
    pub next_object_id: u64,

    /// Player states, indexed by PlayerId.0.
    pub players: Vec<PlayerState>,

    /// Turn structure.
    pub turn_number: u32,
    pub active_player: PlayerId,
    pub priority_player: Option<PlayerId>,
    pub step: Step,

    /// The stack. Last element is top of stack.
    pub stack: Vec<ObjectId>,

    /// Combat state, present only during combat phase.
    pub combat: Option<CombatState>,

    /// Whether the game is waiting for attackers/blockers declaration.
    pub awaiting_action: Option<AwaitingAction>,

    /// Game result, if the game is over.
    pub result: Option<GameResult>,

    /// Number of consecutive priority passes (resets on any non-pass action).
    pub consecutive_passes: u32,

    /// Whether this is the very first turn of the game (skip draw step).
    pub is_first_turn: bool,

    /// Events generated by the most recent action.
    pub events: Vec<crate::events::GameEvent>,

    /// Game log with levels. File gets everything, UI filters by level.
    pub game_log: Vec<LogEntry>,

    /// Temporary effects that expire at end of turn (e.g., Giant Growth's +3/+3).
    pub until_end_of_turn_effects: Vec<UntilEndOfTurnEffect>,

    /// Temporary keyword grants that expire at end of turn.
    pub until_end_of_turn_keywords: Vec<UntilEndOfTurnKeyword>,
}

/// Log level for game log entries.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum LogLevel {
    /// Every priority pass, mana tap, etc.
    Debug = 0,
    /// Actions taken: land plays, phase changes.
    Info = 1,
    /// Important game events: spells cast/resolved, combat, life changes.
    Event = 2,
    /// Major game moments: turn changes, player death, game over.
    Milestone = 3,
}

/// A single log entry with a level.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LogEntry {
    pub level: LogLevel,
    pub message: String,
}

/// A temporary modifier applied to an object that expires at cleanup.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UntilEndOfTurnEffect {
    pub target: ObjectId,
    pub power_mod: i32,
    pub toughness_mod: i32,
}

/// A temporary keyword grant that expires at cleanup.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UntilEndOfTurnKeyword {
    pub target: ObjectId,
    pub keyword: crate::types::Keyword,
}

impl GameState {
    /// Create a new game state for a given number of players.
    pub fn new(num_players: u8) -> Self {
        let players = (0..num_players)
            .map(|i| PlayerState::new(PlayerId(i)))
            .collect();

        Self {
            objects: HashMap::new(),
            next_object_id: 1,
            players,
            turn_number: 1,
            active_player: PlayerId(0),
            priority_player: None,
            step: Step::Untap,
            stack: Vec::new(),
            combat: None,
            awaiting_action: None,
            result: None,
            consecutive_passes: 0,
            is_first_turn: true,
            events: Vec::new(),
            game_log: Vec::new(),
            until_end_of_turn_effects: Vec::new(),
            until_end_of_turn_keywords: Vec::new(),
        }
    }

    /// Allocate a fresh ObjectId.
    pub fn next_id(&mut self) -> ObjectId {
        let id = ObjectId(self.next_object_id);
        self.next_object_id += 1;
        id
    }

    /// Create a new game object and add it to the state.
    pub fn create_object(
        &mut self,
        card_id: CardId,
        owner: PlayerId,
        zone: Zone,
        power: Option<i32>,
        toughness: Option<i32>,
    ) -> ObjectId {
        let id = self.next_id();
        let obj = GameObject {
            id,
            card_id,
            name: String::new(), // Set by caller or setup_game
            owner,
            controller: owner,
            zone,
            tapped: false,
            summoning_sick: zone == Zone::Battlefield,
            damage_marked: 0,
            power,
            toughness,
            colors: Vec::new(),
            targets: Vec::new(),
            attached_to: None,
            zone_change_count: 0,
        };
        self.objects.insert(id, obj);
        id
    }

    /// Move an object to a new zone.
    /// Per MTG rules, changing zones makes it a "new object" — we increment zone_change_count.
    pub fn move_object(&mut self, id: ObjectId, to: Zone) {
        // Collect log info before mutating.
        let log_msg = self.objects.get(&id).and_then(|obj| {
            if obj.zone == Zone::Battlefield && to != Zone::Battlefield && obj.power.is_some() {
                let dest = match to {
                    Zone::Graveyard => "died",
                    Zone::Exile => "was exiled",
                    _ => "left the battlefield",
                };
                Some(format!("{} {}", obj.name, dest))
            } else {
                None
            }
        });

        if let Some(msg) = log_msg {
            self.log(LogLevel::Event, msg);
        }

        if let Some(obj) = self.objects.get_mut(&id) {
            let from = obj.zone;
            obj.zone = to;
            obj.zone_change_count += 1;

            // Reset battlefield-specific state when leaving the battlefield.
            if from == Zone::Battlefield && to != Zone::Battlefield {
                obj.tapped = false;
                obj.summoning_sick = false;
                obj.damage_marked = 0;
                obj.attached_to = None;
            }

            // Set summoning sickness when entering the battlefield.
            if to == Zone::Battlefield && from != Zone::Battlefield {
                obj.summoning_sick = true;
            }
        }
    }

    /// Get an object by ID.
    pub fn get_object(&self, id: ObjectId) -> Option<&GameObject> {
        self.objects.get(&id)
    }

    /// Get a mutable reference to an object by ID.
    pub fn get_object_mut(&mut self, id: ObjectId) -> Option<&mut GameObject> {
        self.objects.get_mut(&id)
    }

    /// Get a player by ID.
    pub fn get_player(&self, id: PlayerId) -> &PlayerState {
        &self.players[id.0 as usize]
    }

    /// Get a mutable reference to a player by ID.
    pub fn get_player_mut(&mut self, id: PlayerId) -> &mut PlayerState {
        &mut self.players[id.0 as usize]
    }

    /// Get all objects in a zone owned/controlled by a player.
    /// For Library/Hand/Graveyard: filter by owner (per rule 400.3).
    /// For Battlefield: filter by controller.
    pub fn objects_in_zone(&self, zone: Zone, player: PlayerId) -> Vec<&GameObject> {
        self.objects.values().filter(|obj| {
            obj.zone == zone && match zone {
                Zone::Library | Zone::Hand | Zone::Graveyard => obj.owner == player,
                Zone::Battlefield => obj.controller == player,
                _ => true,
            }
        }).collect()
    }

    /// Get all objects in a zone (regardless of player).
    pub fn all_objects_in_zone(&self, zone: Zone) -> Vec<&GameObject> {
        self.objects.values().filter(|obj| obj.zone == zone).collect()
    }

    /// Get the next player after the given player (turn order).
    pub fn next_player(&self, player: PlayerId) -> PlayerId {
        let next = (player.0 + 1) % self.players.len() as u8;
        PlayerId(next)
    }

    /// Get the opponent in a 2-player game.
    pub fn opponent(&self, player: PlayerId) -> PlayerId {
        self.next_player(player)
    }

    /// Number of alive players.
    pub fn alive_player_count(&self) -> usize {
        self.players.iter().filter(|p| !p.lost).count()
    }

    /// Add a log entry.
    pub fn log(&mut self, level: LogLevel, msg: String) {
        self.game_log.push(LogEntry { level, message: msg });
    }

    /// Get the effective power of a creature, including continuous effects,
    /// aura bonuses, and "until end of turn" effects.
    pub fn effective_power(&self, id: ObjectId, registry: &crate::cards::CardRegistry) -> Option<i32> {
        let obj = self.get_object(id)?;
        let mut power = obj.power?;

        // Aura/attachment bonuses.
        power += self.aura_power_bonus(id, registry);

        // Global continuous effects (e.g., Glorious Anthem).
        power += self.anthem_power_bonus(id, registry);

        // Until-end-of-turn effects.
        for effect in &self.until_end_of_turn_effects {
            if effect.target == id {
                power += effect.power_mod;
            }
        }

        Some(power)
    }

    /// Get the effective toughness of a creature.
    pub fn effective_toughness(&self, id: ObjectId, registry: &crate::cards::CardRegistry) -> Option<i32> {
        let obj = self.get_object(id)?;
        let mut toughness = obj.toughness?;

        toughness += self.aura_toughness_bonus(id, registry);
        toughness += self.anthem_toughness_bonus(id, registry);

        for effect in &self.until_end_of_turn_effects {
            if effect.target == id {
                toughness += effect.toughness_mod;
            }
        }

        Some(toughness)
    }

    /// Sum power bonuses from attached auras/equipment.
    fn aura_power_bonus(&self, creature_id: ObjectId, registry: &crate::cards::CardRegistry) -> i32 {
        let mut bonus = 0;
        for obj in self.objects.values() {
            if obj.zone == Zone::Battlefield && obj.attached_to == Some(creature_id) {
                if let Some(behavior) = registry.get(obj.card_id) {
                    let data = behavior.card_data();
                    if data.card_types.contains(&crate::types::CardType::Enchantment) {
                        // Check for power bonus in oracle text (simple parsing).
                        bonus += parse_aura_power_bonus(&data.oracle_text);
                    }
                }
            }
        }
        bonus
    }

    fn aura_toughness_bonus(&self, creature_id: ObjectId, registry: &crate::cards::CardRegistry) -> i32 {
        let mut bonus = 0;
        for obj in self.objects.values() {
            if obj.zone == Zone::Battlefield && obj.attached_to == Some(creature_id) {
                if let Some(behavior) = registry.get(obj.card_id) {
                    let data = behavior.card_data();
                    if data.card_types.contains(&crate::types::CardType::Enchantment) {
                        bonus += parse_aura_toughness_bonus(&data.oracle_text);
                    }
                }
            }
        }
        bonus
    }

    /// Sum power bonuses from anthem effects (permanents that boost all your creatures).
    fn anthem_power_bonus(&self, creature_id: ObjectId, registry: &crate::cards::CardRegistry) -> i32 {
        let creature = match self.get_object(creature_id) {
            Some(o) => o,
            None => return 0,
        };
        let controller = creature.controller;
        let mut bonus = 0;

        for obj in self.objects.values() {
            if obj.zone == Zone::Battlefield && obj.controller == controller && obj.id != creature_id {
                if let Some(behavior) = registry.get(obj.card_id) {
                    let data = behavior.card_data();
                    // Simple check: "Creatures you control get +N/+M"
                    if data.oracle_text.contains("Creatures you control get") {
                        bonus += parse_anthem_power(&data.oracle_text);
                    }
                }
            }
        }
        bonus
    }

    fn anthem_toughness_bonus(&self, creature_id: ObjectId, registry: &crate::cards::CardRegistry) -> i32 {
        let creature = match self.get_object(creature_id) {
            Some(o) => o,
            None => return 0,
        };
        let controller = creature.controller;
        let mut bonus = 0;

        for obj in self.objects.values() {
            if obj.zone == Zone::Battlefield && obj.controller == controller && obj.id != creature_id {
                if let Some(behavior) = registry.get(obj.card_id) {
                    let data = behavior.card_data();
                    if data.oracle_text.contains("Creatures you control get") {
                        bonus += parse_anthem_toughness(&data.oracle_text);
                    }
                }
            }
        }
        bonus
    }

    /// Check if a creature is prevented from attacking (e.g., by Pacifism).
    pub fn can_attack(&self, creature_id: ObjectId, registry: &crate::cards::CardRegistry) -> bool {
        // Check for attached auras that prevent attacking.
        for obj in self.objects.values() {
            if obj.zone == Zone::Battlefield && obj.attached_to == Some(creature_id) {
                if let Some(behavior) = registry.get(obj.card_id) {
                    let data = behavior.card_data();
                    if data.oracle_text.contains("can't attack or block") {
                        return false;
                    }
                }
            }
        }
        true
    }

    /// Check if a creature is prevented from blocking.
    pub fn can_block(&self, creature_id: ObjectId, registry: &crate::cards::CardRegistry) -> bool {
        for obj in self.objects.values() {
            if obj.zone == Zone::Battlefield && obj.attached_to == Some(creature_id) {
                if let Some(behavior) = registry.get(obj.card_id) {
                    let data = behavior.card_data();
                    if data.oracle_text.contains("can't attack or block") {
                        return false;
                    }
                }
            }
        }
        true
    }

    /// Check if a creature on the battlefield has a given keyword ability.
    /// Checks static card keywords, aura-granted keywords, and until-EOT grants.
    pub fn has_keyword(&self, creature_id: ObjectId, keyword: crate::types::Keyword, registry: &crate::cards::CardRegistry) -> bool {
        let obj = match self.get_object(creature_id) {
            Some(o) if o.zone == Zone::Battlefield => o,
            _ => return false,
        };

        // 1. Static keywords from card definition.
        if let Some(behavior) = registry.get(obj.card_id) {
            if behavior.card_data().keywords.contains(&keyword) {
                return true;
            }
        }

        // 2. Keywords granted by attached auras/equipment.
        for attached in self.objects.values() {
            if attached.zone == Zone::Battlefield && attached.attached_to == Some(creature_id) {
                if let Some(behavior) = registry.get(attached.card_id) {
                    if behavior.granted_keywords().contains(&keyword) {
                        return true;
                    }
                }
            }
        }

        // 3. Temporary keyword grants (until end of turn).
        for grant in &self.until_end_of_turn_keywords {
            if grant.target == creature_id && grant.keyword == keyword {
                return true;
            }
        }

        false
    }

    /// Is the game over?
    pub fn is_game_over(&self) -> bool {
        self.result.is_some()
    }
}

/// Parse "+N/+M" from aura oracle text like "Enchanted creature gets +1/+2."
fn parse_aura_power_bonus(oracle: &str) -> i32 {
    parse_plus_minus(oracle, 0)
}

fn parse_aura_toughness_bonus(oracle: &str) -> i32 {
    parse_plus_minus(oracle, 1)
}

fn parse_anthem_power(oracle: &str) -> i32 {
    parse_plus_minus(oracle, 0)
}

fn parse_anthem_toughness(oracle: &str) -> i32 {
    parse_plus_minus(oracle, 1)
}

/// Extract the Nth +X/-X value from text like "+1/+2" or "+3/+3".
fn parse_plus_minus(text: &str, index: usize) -> i32 {
    // Find patterns like +1/+2, -1/-1, +3/+3
    for word in text.split_whitespace() {
        if word.contains('/') {
            let parts: Vec<&str> = word.trim_matches('.').split('/').collect();
            if parts.len() == 2 {
                if let Some(part) = parts.get(index) {
                    if let Ok(val) = part.parse::<i32>() {
                        return val;
                    }
                }
            }
        }
    }
    0
}

/// A single game object — an instance of a card on the battlefield, in hand, etc.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GameObject {
    pub id: ObjectId,
    pub card_id: CardId,
    pub name: String,
    pub owner: PlayerId,
    pub controller: PlayerId,
    pub zone: Zone,

    // Battlefield state
    pub tapped: bool,
    pub summoning_sick: bool,
    pub damage_marked: u32,

    // Characteristics (from card data, may be modified by effects later)
    pub power: Option<i32>,
    pub toughness: Option<i32>,
    pub colors: Vec<crate::types::Color>,

    // Targets chosen when this spell was cast (only relevant while on the stack).
    pub targets: Vec<crate::actions::Target>,

    // Aura/equipment: what this is attached to.
    pub attached_to: Option<ObjectId>,

    // Tracks zone changes for staleness detection (XMage pattern).
    pub zone_change_count: u32,
}

/// A player's state.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlayerState {
    pub id: PlayerId,
    pub life: i32,
    pub mana_pool: ManaPool,
    pub land_plays_remaining: u32,
    pub lost: bool,
    pub has_drawn_from_empty: bool,
    /// Order of cards in library (first element is top of library).
    pub library_order: Vec<ObjectId>,
}

impl PlayerState {
    pub fn new(id: PlayerId) -> Self {
        Self {
            id,
            life: 40, // commander starting life
            mana_pool: ManaPool::new(),
            land_plays_remaining: 1,
            lost: false,
            has_drawn_from_empty: false,
            library_order: Vec::new(),
        }
    }

    /// Draw the top card of the library. Returns None if library is empty.
    pub fn draw_top_card(&mut self) -> Option<ObjectId> {
        if self.library_order.is_empty() {
            self.has_drawn_from_empty = true;
            None
        } else {
            Some(self.library_order.remove(0))
        }
    }
}

/// Combat state, tracking attackers and blockers.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CombatState {
    /// Map of attacker ObjectId -> defending PlayerId.
    pub attackers: HashMap<ObjectId, PlayerId>,
    /// Map of attacker ObjectId -> list of blockers assigned to it.
    pub blocker_assignments: HashMap<ObjectId, Vec<ObjectId>>,
}

impl CombatState {
    pub fn new() -> Self {
        Self {
            attackers: HashMap::new(),
            blocker_assignments: HashMap::new(),
        }
    }
}

/// What the engine is waiting for the player to do.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum AwaitingAction {
    DeclareAttackers,
    DeclareBlockers { defending_player: PlayerId },
    DiscardToHandSize { player: PlayerId, discard_count: usize },
}

/// Game result.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum GameResult {
    Winner(PlayerId),
    Draw,
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ids::CardId;

    #[test]
    fn create_and_move_object() {
        let mut state = GameState::new(2);
        let id = state.create_object(CardId(1), PlayerId(0), Zone::Hand, None, None);

        assert_eq!(state.get_object(id).unwrap().zone, Zone::Hand);

        state.move_object(id, Zone::Battlefield);
        let obj = state.get_object(id).unwrap();
        assert_eq!(obj.zone, Zone::Battlefield);
        assert!(obj.summoning_sick);
        assert_eq!(obj.zone_change_count, 1);
    }

    #[test]
    fn objects_in_zone_filters_correctly() {
        let mut state = GameState::new(2);
        let p0 = PlayerId(0);
        let p1 = PlayerId(1);

        state.create_object(CardId(1), p0, Zone::Hand, None, None);
        state.create_object(CardId(2), p0, Zone::Hand, None, None);
        state.create_object(CardId(1), p1, Zone::Hand, None, None);

        assert_eq!(state.objects_in_zone(Zone::Hand, p0).len(), 2);
        assert_eq!(state.objects_in_zone(Zone::Hand, p1).len(), 1);
    }

    #[test]
    fn leaving_battlefield_resets_state() {
        let mut state = GameState::new(2);
        let id = state.create_object(CardId(1), PlayerId(0), Zone::Battlefield, Some(2), Some(2));

        {
            let obj = state.get_object_mut(id).unwrap();
            obj.tapped = true;
            obj.damage_marked = 1;
        }

        state.move_object(id, Zone::Graveyard);
        let obj = state.get_object(id).unwrap();
        assert!(!obj.tapped);
        assert_eq!(obj.damage_marked, 0);
        assert!(!obj.summoning_sick);
    }

    #[test]
    fn draw_from_empty_library() {
        let mut state = GameState::new(2);
        let player = state.get_player_mut(PlayerId(0));
        assert!(player.draw_top_card().is_none());
        assert!(player.has_drawn_from_empty);
    }
}
