use std::collections::HashMap;

use serde::{Serialize, Deserialize};

use crate::ids::{ObjectId, PlayerId, CardId};
use crate::types::{Zone, Step, ManaPool};

/// An entry on the stack — either a spell or a triggered ability.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum StackEntry {
    /// A spell (instant, sorcery, creature, etc.) on the stack.
    Spell(ObjectId),
    /// A triggered ability on the stack. Resolves by calling the card behavior.
    Trigger(crate::triggers::PendingTrigger),
}

impl StackEntry {
    /// Get the ObjectId if this is a spell.
    pub fn as_spell(&self) -> Option<ObjectId> {
        match self {
            StackEntry::Spell(id) => Some(*id),
            StackEntry::Trigger(_) => None,
        }
    }

    /// Get the trigger if this is a triggered ability.
    pub fn as_trigger(&self) -> Option<&crate::triggers::PendingTrigger> {
        match self {
            StackEntry::Trigger(t) => Some(t),
            StackEntry::Spell(_) => None,
        }
    }

    /// Description for display purposes.
    pub fn display_name(&self, registry: &crate::cards::CardRegistry) -> String {
        match self {
            StackEntry::Spell(id) => format!("Spell({})", id.0),
            StackEntry::Trigger(t) => t.display_name(registry),
        }
    }
}

/// The complete, immutable game state. Clone to produce new states.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GameState {
    /// All game objects keyed by their unique ID.
    pub objects: HashMap<ObjectId, GameObject>,
    /// Monotonic counter for generating unique ObjectIds.
    pub next_object_id: u64,

    /// Player states, indexed by PlayerId.0.
    pub players: Vec<PlayerState>,

    /// Turn structure.
    pub turn_number: u32,
    pub active_player: PlayerId,
    pub priority_player: Option<PlayerId>,
    pub step: Step,

    /// The stack. Last element is top of stack. Contains spells and triggered abilities.
    pub stack: Vec<StackEntry>,

    /// Combat state, present only during combat phase.
    pub combat: Option<CombatState>,

    /// Objects to exile at end of combat (delayed triggers like Geist of Saint Traft's Angel).
    /// These fire independently of the source permanent's presence on the battlefield.
    pub end_of_combat_exiles: Vec<ObjectId>,

    /// Whether the game is waiting for attackers/blockers declaration.
    pub awaiting_action: Option<AwaitingAction>,

    /// Game result, if the game is over.
    pub result: Option<GameResult>,

    /// Number of consecutive priority passes (resets on any non-pass action).
    pub consecutive_passes: u32,

    /// Whether this is the very first turn of the game (skip draw step).
    pub is_first_turn: bool,

    /// Events generated by the most recent action.
    pub events: Vec<crate::events::GameEvent>,

    /// Game log with levels. File gets everything, UI filters by level.
    pub game_log: Vec<LogEntry>,

    /// All temporary effects that expire at end of turn (cleanup step).
    #[serde(default)]
    pub until_end_of_turn: Vec<TemporaryEffect>,

    /// Whether a creature has died this turn (for morbid).
    #[serde(default)]
    pub creature_died_this_turn: bool,

    /// Day/night state for werewolf transform tracking.
    #[serde(default)]
    pub day_night: Option<DayNight>,

    /// Number of spells cast this turn by each player (for werewolf transforms).
    #[serde(default)]
    pub num_spells_cast_this_turn: HashMap<PlayerId, u32>,

    /// Spells cast last turn (saved at turn start for werewolf condition checking).
    #[serde(default)]
    pub num_spells_cast_last_turn: HashMap<PlayerId, u32>,

    /// X value chosen for the most recently activated X-cost ability.
    /// Set by the engine before calling on_activate_ability; cards read this.
    #[serde(default)]
    pub last_activated_x_value: Option<u32>,

    /// Index for trigger processing resumption after a resolution choice.
    #[serde(default)]
    pub trigger_event_index: usize,

    /// Pending triggered abilities waiting to resolve, in APNAP order.
    /// Active player's triggers at the front (bottom of "stack"),
    /// non-active player's at the back (top). Resolved LIFO from the back.
    #[serde(default)]
    pub pending_triggers: Vec<crate::triggers::PendingTrigger>,

    /// Queue of (player, bottom_count) pairs waiting for the London-mulligan
    /// bottoming sub-phase. Populated as each player finishes their keep/mull
    /// decision. Drained by `advance_mulligan_phase`.
    #[serde(default)]
    pub pending_mulligan_bottoms: Vec<(PlayerId, usize)>,

    /// Position within the current London-mulligan round, indexed from
    /// the active player. Within a round each non-kept player makes one
    /// keep/mull decision in turn order. When `mulligan_round_position`
    /// reaches the player count, the round ends.
    #[serde(default)]
    pub mulligan_round_position: u8,

    /// Whether any player has chosen `MulliganMull` in the current
    /// London-mulligan round. Used at end-of-round to decide whether to
    /// start a new round or transition to bottoming.
    #[serde(default)]
    pub mulligan_round_mulled: bool,
}

/// Log level for game log entries.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum LogLevel {
    /// Every priority pass, mana tap, etc.
    Debug = 0,
    /// Actions taken: land plays, phase changes.
    Info = 1,
    /// Important game events: spells cast/resolved, combat, life changes.
    Event = 2,
    /// Major game moments: turn changes, player death, game over.
    Milestone = 3,
}

/// A single log entry with a level.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LogEntry {
    pub level: LogLevel,
    pub message: String,
}

/// A temporary effect that expires during the cleanup step.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum TemporaryEffect {
    /// Modify power and/or toughness (e.g., Giant Growth +3/+3).
    ModifyPT { target: ObjectId, power_mod: i32, toughness_mod: i32 },
    /// Grant a keyword (e.g., Moment of Heroism grants lifelink).
    GrantKeyword { target: ObjectId, keyword: crate::types::Keyword },
    /// Remove a keyword (e.g., Manor Gargoyle loses defender).
    RemoveKeyword { target: ObjectId, keyword: crate::types::Keyword },
    /// Creature can't block this turn (e.g., Nightbird's Clutches).
    CantBlock { target: ObjectId },
    /// Grant protection from creatures matching a filter (e.g., Spare from Evil).
    GrantProtection { target: ObjectId, filter: crate::types::CreatureFilter },
    /// Temporary control change; reverts at cleanup (e.g., Traitorous Blood).
    ChangeControl { target: ObjectId, original_controller: PlayerId },
    /// Grant flashback to a card in the graveyard (e.g., Snapcaster Mage).
    GrantFlashback { target: ObjectId, cost: crate::types::ManaCost },
    /// Prevent combat damage from non-Wolf/Werewolf creatures (Moonmist).
    PreventNonWolfWerewolfCombatDamage,
    /// Blanket P/T modifier — applies to all creatures matching a filter.
    /// Used by anthems like Rally the Peasants ("creatures you control get +2/+0").
    ModifyPTAll {
        controller: PlayerId,
        filter: Option<crate::types::CreatureFilter>,
        power_mod: i32,
        toughness_mod: i32,
    },
    /// Blanket keyword grant — applies to all creatures matching a filter.
    /// Used by Vampiric Fury ("Vampire creatures you control gain first strike").
    GrantKeywordAll {
        controller: PlayerId,
        filter: Option<crate::types::CreatureFilter>,
        keyword: crate::types::Keyword,
    },
    /// Blanket protection grant — applies to all creatures controlled by a player.
    /// Used by Spare from Evil ("creatures you control gain protection from non-Human").
    GrantProtectionAll {
        controller: PlayerId,
        protection_filter: crate::types::CreatureFilter,
    },
    /// P/T modifier that disappears if source leaves the battlefield.
    /// Used by static abilities like Instigator Gang's "attacking creatures get +1/+0".
    ModifyPTWhileSourceInPlay {
        target: ObjectId,
        source: ObjectId,
        power_mod: i32,
        toughness_mod: i32,
    },
}

impl GameState {
    /// Create a new game state for a given number of players.
    pub fn new(num_players: u8) -> Self {
        let players = (0..num_players)
            .map(|i| PlayerState::new(PlayerId(i)))
            .collect();

        Self {
            objects: HashMap::new(),
            next_object_id: 1,
            players,
            turn_number: 1,
            active_player: PlayerId(0),
            priority_player: None,
            step: Step::Untap,
            stack: Vec::new(),
            combat: None,
            end_of_combat_exiles: Vec::new(),
            awaiting_action: None,
            result: None,
            consecutive_passes: 0,
            is_first_turn: true,
            events: Vec::new(),
            game_log: Vec::new(),
            until_end_of_turn: Vec::new(),
            creature_died_this_turn: false,
            day_night: None,
            num_spells_cast_this_turn: HashMap::new(),
            num_spells_cast_last_turn: HashMap::new(),
            last_activated_x_value: None,
            trigger_event_index: 0,
            pending_triggers: Vec::new(),
            pending_mulligan_bottoms: Vec::new(),
            mulligan_round_position: 0,
            mulligan_round_mulled: false,
        }
    }

    /// Allocate a fresh ObjectId.
    pub fn next_id(&mut self) -> ObjectId {
        let id = ObjectId(self.next_object_id);
        self.next_object_id += 1;
        id
    }

    /// Create a new game object and add it to the state.
    pub fn create_object(
        &mut self,
        card_id: CardId,
        owner: PlayerId,
        zone: Zone,
        power: Option<i32>,
        toughness: Option<i32>,
    ) -> ObjectId {
        let id = self.next_id();
        let obj = GameObject {
            id,
            card_id,
            name: String::new(), // Set by caller or setup_game
            owner,
            controller: owner,
            zone,
            tapped: false,
            summoning_sick: zone == Zone::Battlefield,
            damage_marked: 0,
            dealt_deathtouch_damage: false, damaged_by: Vec::new(),
            power,
            toughness,
            colors: Vec::new(),
            keywords: Vec::new(),
            card_types: Vec::new(),
            subtypes: Vec::new(),
            targets: Vec::new(),
            attached_to: None,
            attached_to_player: None,
            zone_change_count: 0,
            is_token: false,
            is_legendary: false,
            cast_with_flashback: false,
            instance_oracle_text: None,
            instance_continuous_effects: None,
            card_state: HashMap::new(),
            counters: HashMap::new(),
            regeneration_shields: 0,
            is_equipment: false,
            is_transformed: false,
            x_value: None,
            chosen_mode: None,
            abilities_activated_this_turn: std::collections::HashSet::new(),
            entering_copy_source: false,
            state_trigger_on_stack: false,
        };
        self.objects.insert(id, obj);
        id
    }

    /// Create a token on the battlefield. Returns all created IDs
    /// (primary + Parallel Lives extras).
    pub fn create_token(
        &mut self,
        name: &str,
        owner: PlayerId,
        power: i32,
        toughness: i32,
        colors: Vec<crate::types::Color>,
        card_types: Vec<crate::types::CardType>,
        keywords: Vec<crate::types::Keyword>,
        registry: &crate::cards::CardRegistry,
    ) -> Vec<ObjectId> {
        self.create_token_with_subtypes(name, owner, power, toughness, colors, card_types, keywords, vec![], registry)
    }

    /// Create a token on the battlefield with specific creature subtypes.
    /// If a permanent with ReplacementEffect::DoubleTokens is on the battlefield
    /// under the same controller, extra copies of the token are created.
    pub fn create_token_with_subtypes(
        &mut self,
        name: &str,
        owner: PlayerId,
        power: i32,
        toughness: i32,
        colors: Vec<crate::types::Color>,
        card_types: Vec<crate::types::CardType>,
        keywords: Vec<crate::types::Keyword>,
        subtypes: Vec<String>,
        registry: &crate::cards::CardRegistry,
    ) -> Vec<ObjectId> {
        // Check for token-doubling replacement effects (e.g. Parallel Lives).
        let doubler_count = self.objects.values()
            .filter(|o| o.zone == Zone::Battlefield && o.controller == owner)
            .filter(|o| {
                registry.get(o.card_id)
                    .map(|b| b.replacement_effects().contains(&crate::types::ReplacementEffect::DoubleTokens))
                    .unwrap_or(false)
            })
            .count();
        // Each doubler doubles, so 1 = 2x, 2 = 4x, etc.
        // We create (2^N - 1) extra tokens.
        let extra_copies = if doubler_count > 0 {
            (1u32 << doubler_count) - 1
        } else {
            0
        };

        let mut all_ids = Vec::new();

        // Create the primary token.
        let id = self.create_token_internal(name, owner, power, toughness,
            colors.clone(), card_types.clone(), keywords.clone(), subtypes.clone(), registry);
        all_ids.push(id);

        // Create extra copies for token doublers.
        for _ in 0..extra_copies {
            let extra = self.create_token_internal(name, owner, power, toughness,
                colors.clone(), card_types.clone(), keywords.clone(), subtypes.clone(), registry);
            all_ids.push(extra);
        }

        all_ids
    }

    /// Internal token creation without Parallel Lives doubling.
    fn create_token_internal(
        &mut self,
        name: &str,
        owner: PlayerId,
        power: i32,
        toughness: i32,
        colors: Vec<crate::types::Color>,
        card_types: Vec<crate::types::CardType>,
        keywords: Vec<crate::types::Keyword>,
        subtypes: Vec<String>,
        registry: &crate::cards::CardRegistry,
    ) -> ObjectId {
        let id = self.next_id();
        let obj = GameObject {
            id,
            card_id: CardId(0), // sentinel for tokens
            name: name.to_string(),
            owner,
            controller: owner,
            zone: Zone::Battlefield,
            tapped: false,
            summoning_sick: true,
            damage_marked: 0,
            dealt_deathtouch_damage: false, damaged_by: Vec::new(),
            power: Some(power),
            toughness: Some(toughness),
            colors,
            keywords,
            card_types,
            subtypes,
            targets: Vec::new(),
            attached_to: None,
            attached_to_player: None,
            zone_change_count: 0,
            is_token: true,
            is_legendary: false,
            cast_with_flashback: false,
            instance_oracle_text: None,
            instance_continuous_effects: None,
            card_state: HashMap::new(),
            counters: HashMap::new(),
            regeneration_shields: 0,
            is_equipment: false,
            is_transformed: false,
            x_value: None,
            abilities_activated_this_turn: std::collections::HashSet::new(),
            chosen_mode: None,
            entering_copy_source: false,
            state_trigger_on_stack: false,
        };
        self.objects.insert(id, obj);
        // Apply entering-battlefield replacement effects (CR 614.1d) for tokens too.
        self.apply_entering_copy_replacement(id, registry);

        // CR 614.1c: Apply "enters with" counters for tokens.
        let token_counters = self.compute_entering_counters(id, None, registry);
        for (counter_type, count) in &token_counters {
            self.add_counters(id, *counter_type, *count);
        }

        let controller = self.get_object(id).map(|o| o.controller).unwrap_or(owner);
        self.events.push(crate::events::GameEvent::EnteredBattlefield {
            object: id,
            controller,
        });
        id
    }

    /// Create a token that copies all characteristics of a source permanent.
    /// Used by Cackling Counterpart, Evil Twin, etc.
    pub fn create_token_copy(
        &mut self,
        source_id: ObjectId,
        owner: PlayerId,
        registry: &crate::cards::CardRegistry,
    ) -> ObjectId {
        let source = self.get_object(source_id);
        let (name, power, toughness, card_id, is_legendary) = match source {
            Some(o) => (o.name.clone(), o.power, o.toughness, o.card_id, o.is_legendary),
            None => return ObjectId(0),
        };
        let (colors, keywords, card_types, subtypes) = registry.card_data(card_id)
            .map(|d| {
                // Derive colors from mana cost.
                let mut cols = Vec::new();
                if let Some(ref cost) = d.cost {
                    for sym in &cost.symbols {
                        if let crate::types::ManaSymbol::Colored(c) = sym {
                            if !cols.contains(c) {
                                cols.push(*c);
                            }
                        }
                    }
                }
                (cols, d.keywords.clone(), d.card_types.clone(), d.subtypes.clone())
            })
            .unwrap_or_default();

        let all_ids = self.create_token_with_subtypes(
            &name,
            owner,
            power.unwrap_or(0),
            toughness.unwrap_or(0),
            colors,
            card_types,
            keywords,
            subtypes.iter().map(|s| s.to_string()).collect(),
            registry,
        );
        // Copy the card_id and is_legendary so ALL tokens (including Parallel Lives extras)
        // get the same CardBehavior and are correctly flagged for the legend rule.
        for &token_id in &all_ids {
            if let Some(obj) = self.get_object_mut(token_id) {
                obj.card_id = card_id;
                obj.is_legendary = is_legendary;
            }
        }
        all_ids.into_iter().next().unwrap_or(ObjectId(0))
    }

    /// Move an object to a new zone.
    /// Per MTG rules, changing zones makes it a "new object" — we increment zone_change_count.
    pub fn move_object(&mut self, id: ObjectId, to: Zone, registry: &crate::cards::CardRegistry) {
        // Collect log info before mutating.
        let log_msg = self.objects.get(&id).and_then(|obj| {
            if obj.zone == Zone::Battlefield && to != Zone::Battlefield && obj.power.is_some() {
                let dest = match to {
                    Zone::Graveyard => "died",
                    Zone::Exile => "was exiled",
                    _ => "left the battlefield",
                };
                Some(format!("{} {}", obj.name, dest))
            } else {
                None
            }
        });

        if let Some(msg) = log_msg {
            self.log(LogLevel::Event, msg);
        }

        let from = self.objects.get(&id).map(|o| o.zone);
        // Capture controller before any mutation: CR 603.10c requires LTB
        // triggers to be controlled by whoever controlled the permanent
        // immediately before it left the battlefield.
        let pre_move_controller = self.objects.get(&id).map(|o| o.controller);

        // CR 614.1c: Compute "enters with" counters BEFORE the zone change,
        // so graveyard counts still include this creature if entering from GY.
        let entering_counters = if to == Zone::Battlefield && from.map(|z| z != Zone::Battlefield).unwrap_or(false) {
            self.compute_entering_counters(id, from, registry)
        } else {
            vec![]
        };

        if let Some(obj) = self.objects.get_mut(&id) {
            let from = obj.zone;
            obj.zone = to;
            obj.zone_change_count += 1;

            // Reset battlefield-specific state when leaving the battlefield.
            // Note: card_state is NOT cleared here — LTB triggers need it
            // (e.g., Fiend Hunter's "exiled_creature"). It's cleared on re-entry.
            if from == Zone::Battlefield && to != Zone::Battlefield {
                obj.tapped = false;
                obj.summoning_sick = false;
                obj.damage_marked = 0;
                obj.dealt_deathtouch_damage = false; obj.damaged_by.clear();
                obj.attached_to = None;
                obj.counters.clear();
                obj.regeneration_shields = 0;
                obj.is_transformed = false;
                obj.instance_continuous_effects = None;
                obj.instance_oracle_text = None;
            }

            // Set summoning sickness and clear stale state when entering the battlefield.
            if to == Zone::Battlefield && from != Zone::Battlefield {
                obj.card_state.clear();
                obj.summoning_sick = true;
            }
        }

        // Emit zone-change events outside the mutable borrow.
        if let Some(from_zone) = from {
            if from_zone == Zone::Battlefield && to != Zone::Battlefield {
                self.events.push(crate::events::GameEvent::LeftBattlefield {
                    object: id,
                    to,
                    last_controller: pre_move_controller.unwrap_or(PlayerId(0)),
                });
            }
            if to == Zone::Battlefield && from_zone != Zone::Battlefield {
                // Apply entering-battlefield replacement effects (CR 614.1d).
                self.apply_entering_copy_replacement(id, registry);

                // CR 614.1c: Apply pre-computed "enters with" counters.
                for (counter_type, count) in &entering_counters {
                    self.add_counters(id, *counter_type, *count);
                }

                let controller = self.get_object(id).map(|o| o.controller).unwrap_or(PlayerId(0));
                self.events.push(crate::events::GameEvent::EnteredBattlefield {
                    object: id,
                    controller,
                });
            }
        }
    }

    /// Apply entering-battlefield copy replacement effects (CR 614.1d).
    /// If any permanent with `ReplacementEffect::EnterAsCopy` is on the battlefield
    /// under the same controller as `entering_id`, the entering creature's characteristics
    /// are replaced with those of the copy source. The entering creature keeps its own
    /// identity (ObjectId, owner, controller) but gains the source's copiable values.
    fn apply_entering_copy_replacement(&mut self, entering_id: ObjectId, registry: &crate::cards::CardRegistry) {
        // Get the entering creature's controller and check it's a creature.
        let (controller, is_creature) = match self.get_object(entering_id) {
            Some(o) => (o.controller, o.power.is_some()),
            None => return,
        };
        if !is_creature {
            return;
        }

        // Find a copy source on the battlefield under the same controller.
        // The entering creature itself cannot be its own copy source.
        // Check for ReplacementEffect::EnterAsCopy via the card registry.
        // Find the source permanent and get its card data for copiable values.
        let source_info: Option<(crate::ids::CardId, String)> = self.objects.values()
            .find(|o| {
                o.zone == Zone::Battlefield
                    && o.controller == controller
                    && o.id != entering_id
                    && registry.get(o.card_id)
                        .map(|b| b.replacement_effects().contains(&crate::types::ReplacementEffect::EnterAsCopy))
                        .unwrap_or(false)
            })
            .map(|source| (source.card_id, source.name.clone()));

        // Get copiable values from card data (the authoritative source for characteristics).
        let source_data = source_info.and_then(|(card_id, name)| {
            registry.card_data(card_id).map(|d| {
                (
                    name,
                    d.power.unwrap_or(0),
                    d.toughness.unwrap_or(0),
                    // Derive colors from mana cost.
                    d.cost.as_ref().map(|c| {
                        let mut cols = Vec::new();
                        for sym in &c.symbols {
                            if let crate::types::ManaSymbol::Colored(c) = sym {
                                if !cols.contains(c) { cols.push(*c); }
                            }
                        }
                        cols
                    }).unwrap_or_default(),
                    d.card_types.clone(),
                    d.subtypes.clone(),
                    d.keywords.clone(),
                    d.oracle_text.clone(),
                )
            })
        });

        if let Some((name, power, toughness, colors, card_types, subtypes, keywords, oracle_text)) = source_data {
            let old_name = self.get_object(entering_id).map(|o| o.name.clone()).unwrap_or_default();
            if let Some(obj) = self.get_object_mut(entering_id) {
                obj.name = name.clone();
                obj.power = Some(power);
                obj.toughness = Some(toughness);
                obj.colors = colors;
                obj.card_types = card_types;
                obj.subtypes = subtypes;
                obj.keywords = keywords;
                obj.instance_continuous_effects = Some(vec![]);
                obj.instance_oracle_text = Some(oracle_text);
            }
            self.log(LogLevel::Event,
                format!("{} enters as a copy of {} ({}/{})", old_name, name, power, toughness));
        }
    }

    /// CR 614.1c: Compute all "enters with" counters for a creature about to
    /// enter the battlefield. Called BEFORE the zone change so graveyard counts
    /// are accurate (e.g. Unbreathing Horde counts itself when entering from GY).
    fn compute_entering_counters(
        &self,
        entering_id: ObjectId,
        from_zone: Option<Zone>,
        registry: &crate::cards::CardRegistry,
    ) -> Vec<(crate::types::CounterType, u32)> {
        let card_id = match self.get_object(entering_id) {
            Some(o) => o.card_id,
            None => return vec![],
        };

        let mut counters = Vec::new();

        // 1. Self "enters with" counters (Festerhide Boar, Unbreathing Horde, etc.)
        if let Some(behavior) = registry.get(card_id) {
            let self_counters = behavior.entering_with_counters(self, entering_id, from_zone, registry);
            counters.extend(self_counters);
        }

        // 2. External modifiers (Dearly Departed in graveyard, etc.)
        let entering_controller = self.get_object(entering_id).map(|o| o.controller).unwrap_or(PlayerId(0));
        for obj in self.objects.values() {
            if obj.id == entering_id { continue; }
            if let Some(behavior) = registry.get(obj.card_id) {
                let zones = behavior.entering_modifier_zones();
                if zones.contains(&obj.zone) {
                    let extra = behavior.modify_creature_entering_counters(
                        self, obj.id, entering_id, entering_controller, registry,
                    );
                    counters.extend(extra);
                }
            }
        }

        counters
    }

    /// Get an object by ID.
    pub fn get_object(&self, id: ObjectId) -> Option<&GameObject> {
        self.objects.get(&id)
    }

    /// Return "CardName (#id)" for use in log messages.
    pub fn obj_name(&self, id: ObjectId) -> String {
        let name = self.get_object(id)
            .map(|o| o.name.clone())
            .unwrap_or_else(|| "?".into());
        format!("{} (#{})", name, id.0)
    }

    /// Get a mutable reference to an object by ID.
    pub fn get_object_mut(&mut self, id: ObjectId) -> Option<&mut GameObject> {
        self.objects.get_mut(&id)
    }

    /// Get a player by ID.
    pub fn get_player(&self, id: PlayerId) -> &PlayerState {
        &self.players[id.0 as usize]
    }

    /// Get a mutable reference to a player by ID.
    pub fn get_player_mut(&mut self, id: PlayerId) -> &mut PlayerState {
        &mut self.players[id.0 as usize]
    }

    /// Get all objects in a zone owned/controlled by a player.
    /// For Library/Hand/Graveyard: filter by owner (per rule 400.3).
    /// For Battlefield: filter by controller.
    pub fn objects_in_zone(&self, zone: Zone, player: PlayerId) -> Vec<&GameObject> {
        let mut result: Vec<_> = self.objects.values().filter(|obj| {
            obj.zone == zone && match zone {
                Zone::Library | Zone::Hand | Zone::Graveyard => obj.owner == player,
                Zone::Battlefield => obj.controller == player,
                _ => true,
            }
        }).collect();
        result.sort_by_key(|o| o.id);
        result
    }

    /// Get all objects in a zone (regardless of player).
    pub fn all_objects_in_zone(&self, zone: Zone) -> Vec<&GameObject> {
        let mut result: Vec<_> = self.objects.values().filter(|obj| obj.zone == zone).collect();
        result.sort_by_key(|o| o.id);
        result
    }

    /// Get the next player after the given player (turn order).
    pub fn next_player(&self, player: PlayerId) -> PlayerId {
        let next = (player.0 + 1) % self.players.len() as u8;
        PlayerId(next)
    }

    /// Get the opponent in a 2-player game.
    pub fn opponent(&self, player: PlayerId) -> PlayerId {
        self.next_player(player)
    }

    /// Number of alive players.
    pub fn alive_player_count(&self) -> usize {
        self.players.iter().filter(|p| !p.lost).count()
    }

    /// Add a log entry.
    pub fn log(&mut self, level: LogLevel, msg: String) {
        self.game_log.push(LogEntry { level, message: msg });
    }

    /// Check if a creature matches a CreatureFilter, evaluated from the perspective
    /// of the effect's source permanent.
    pub fn matches_filter(
        &self,
        creature_id: ObjectId,
        filter: &crate::types::CreatureFilter,
        source_controller: PlayerId,
        registry: &crate::cards::CardRegistry,
    ) -> bool {
        use crate::types::CreatureFilter;
        let creature = match self.get_object(creature_id) {
            Some(o) => o,
            None => return false,
        };
        match filter {
            CreatureFilter::ControlledByYou => creature.controller == source_controller,
            CreatureFilter::ControlledByOpponent => creature.controller != source_controller,
            CreatureFilter::ControlledByYouToken => creature.controller == source_controller && creature.is_token,
            CreatureFilter::HasSubtype(subtype) => {
                // For transformed DFCs, use back face subtypes instead of front face.
                if creature.is_transformed {
                    if let Some(behavior) = registry.get(creature.card_id) {
                        if let Some(back) = behavior.back_face_data() {
                            if back.subtypes.iter().any(|s| s == subtype) {
                                return true;
                            }
                        }
                    }
                } else {
                    // Check card data subtypes first, then object-level subtypes (for tokens).
                    if registry.card_data(creature.card_id)
                        .map(|d| d.subtypes.iter().any(|s| s == subtype))
                        .unwrap_or(false) {
                        return true;
                    }
                }
                creature.subtypes.iter().any(|s| s == subtype)
            }
            CreatureFilter::HasKeyword(kw) => self.has_keyword(creature_id, *kw, registry),
            CreatureFilter::And(filters) => filters.iter().all(|f| self.matches_filter(creature_id, f, source_controller, registry)),
            CreatureFilter::Or(filters) => filters.iter().any(|f| self.matches_filter(creature_id, f, source_controller, registry)),
            CreatureFilter::Not(inner) => !self.matches_filter(creature_id, inner, source_controller, registry),
            CreatureFilter::ControlledByAttachedPlayer => {
                // This filter requires knowing the source object's attached_to_player.
                // It's resolved in effect_applies_to which has source_id.
                // If called directly from matches_filter without source context,
                // fall back to Opponents (the common case for curses).
                creature.controller != source_controller
            }
        }
    }

    /// Check if a continuous effect applies to a given creature.
    pub fn effect_applies_to(
        &self,
        creature_id: ObjectId,
        scope: &crate::types::EffectScope,
        source_id: ObjectId,
        source_controller: PlayerId,
        registry: &crate::cards::CardRegistry,
    ) -> bool {
        use crate::types::EffectScope;
        match scope {
            EffectScope::OnSelf => creature_id == source_id,
            EffectScope::Attached => {
                self.get_object(source_id)
                    .and_then(|o| o.attached_to)
                    .map(|target| target == creature_id)
                    .unwrap_or(false)
            }
            EffectScope::Global(filter) => {
                // For AttachedPlayer filter, use the source's attached_to_player.
                if matches!(filter, crate::types::CreatureFilter::ControlledByAttachedPlayer) {
                    let attached_player = self.get_object(source_id)
                        .and_then(|o| o.attached_to_player);
                    if let Some(player) = attached_player {
                        let creature = self.get_object(creature_id);
                        return creature.map(|c| c.controller == player).unwrap_or(false);
                    }
                    return false;
                }
                self.matches_filter(creature_id, filter, source_controller, registry)
            }
            EffectScope::GlobalOther(filter) => {
                creature_id != source_id && self.matches_filter(creature_id, filter, source_controller, registry)
            }
        }
    }

    /// Collect all (power_mod, toughness_mod) from continuous effects that apply to a creature.
    fn continuous_pt_mods(&self, creature_id: ObjectId, registry: &crate::cards::CardRegistry) -> (i32, i32) {
        use crate::types::ContinuousEffect;
        let mut power = 0;
        let mut toughness = 0;
        for source in self.objects.values() {
            if source.zone != Zone::Battlefield {
                continue;
            }
            // Check instance-level effects first (e.g., Bonds of Faith).
            if let Some(ref instance_effects) = source.instance_continuous_effects {
                for effect in instance_effects {
                    if let ContinuousEffect::ModifyPT { power: p, toughness: t, scope } = effect {
                        if self.effect_applies_to(creature_id, scope, source.id, source.controller, registry) {
                            power += p;
                            toughness += t;
                        }
                    }
                }
            } else if let Some(behavior) = registry.get(source.card_id) {
                // Card-level static effects (use back face if transformed).
                let effects = if source.is_transformed {
                    behavior.back_face_data().map(|d| d.continuous_effects).unwrap_or_default()
                } else {
                    behavior.card_data().continuous_effects
                };
                for effect in &effects {
                    match effect {
                        ContinuousEffect::ModifyPT { power: p, toughness: t, scope } => {
                            if self.effect_applies_to(creature_id, scope, source.id, source.controller, registry) {
                                power += p;
                                toughness += t;
                            }
                        }
                        ContinuousEffect::ConditionalModifyPT { power: p, toughness: t, condition, scope } => {
                            if self.effect_applies_to(creature_id, scope, source.id, source.controller, registry)
                                && self.check_condition(condition, source.id, source.controller, registry) {
                                power += p;
                                toughness += t;
                            }
                        }
                        _ => {}
                    }
                }
                // Dynamic P/T from auras (e.g., Wreath of Geists: +X/+X where X = creatures in graveyard).
                if source.attached_to == Some(creature_id) {
                    if let Some((p, t)) = behavior.dynamic_pt(self, source.id) {
                        power += p;
                        toughness += t;
                    }
                }
            }
        }
        (power, toughness)
    }

    /// Check if a creature has a specific continuous effect applying to it.
    pub fn has_continuous_effect(
        &self,
        creature_id: ObjectId,
        predicate: &dyn Fn(&crate::types::ContinuousEffect) -> Option<&crate::types::EffectScope>,
        registry: &crate::cards::CardRegistry,
    ) -> bool {
        for source in self.objects.values() {
            if source.zone != Zone::Battlefield {
                continue;
            }
            // Check instance-level effects first.
            if let Some(ref instance_effects) = source.instance_continuous_effects {
                for effect in instance_effects {
                    if let Some(scope) = predicate(effect) {
                        if self.effect_applies_to(creature_id, scope, source.id, source.controller, registry) {
                            return true;
                        }
                    }
                }
            } else if let Some(behavior) = registry.get(source.card_id) {
                // Use back face effects when transformed.
                let effects = if source.is_transformed {
                    behavior.back_face_data().map(|d| d.continuous_effects).unwrap_or_default()
                } else {
                    behavior.card_data().continuous_effects
                };
                for effect in &effects {
                    if let Some(scope) = predicate(effect) {
                        if self.effect_applies_to(creature_id, scope, source.id, source.controller, registry) {
                            return true;
                        }
                    }
                }
            }
        }
        false
    }

    /// Count how many sources apply a matching continuous effect to a creature.
    /// Similar to has_continuous_effect but returns the count instead of a boolean.
    pub fn count_continuous_effect(
        &self,
        creature_id: ObjectId,
        predicate: &dyn Fn(&crate::types::ContinuousEffect) -> Option<&crate::types::EffectScope>,
        registry: &crate::cards::CardRegistry,
    ) -> u32 {
        let mut count = 0;
        for source in self.objects.values() {
            if source.zone != Zone::Battlefield {
                continue;
            }
            if let Some(ref instance_effects) = source.instance_continuous_effects {
                for effect in instance_effects {
                    if let Some(scope) = predicate(effect) {
                        if self.effect_applies_to(creature_id, scope, source.id, source.controller, registry) {
                            count += 1;
                        }
                    }
                }
            } else if let Some(behavior) = registry.get(source.card_id) {
                let effects = if source.is_transformed {
                    behavior.back_face_data().map(|d| d.continuous_effects).unwrap_or_default()
                } else {
                    behavior.card_data().continuous_effects
                };
                for effect in &effects {
                    if let Some(scope) = predicate(effect) {
                        if self.effect_applies_to(creature_id, scope, source.id, source.controller, registry) {
                            count += 1;
                        }
                    }
                }
            }
        }
        count
    }

    /// Get the effective power of a creature, including continuous effects,
    /// dynamic P/T, counters, and "until end of turn" effects.
    pub fn effective_power(&self, id: ObjectId, registry: &crate::cards::CardRegistry) -> Option<i32> {
        let obj = self.get_object(id)?;

        // Check if this token has dynamic P/T tied to counter count on a source permanent
        // (e.g., Gutter Grime Ooze tokens whose P/T = slime counters on Gutter Grime).
        let mut power = if let Some(source_id) = obj.card_state.get("pt_source_counter") {
            let counter_type_val = obj.card_state.get("pt_source_counter_type")
                .map(|v| v.0).unwrap_or(0);
            let counter_type = match counter_type_val {
                1 => crate::types::CounterType::Slime,
                _ => crate::types::CounterType::PlusOnePlusOne,
            };
            self.get_object(*source_id)
                .map(|src| *src.counters.get(&counter_type).unwrap_or(&0) as i32)
                .unwrap_or(0)
        } else if let Some(behavior) = registry.get(obj.card_id) {
            // Check if this creature's own card has dynamic P/T (e.g., Geist-Honored Monk).
            if let Some((p, _)) = behavior.dynamic_pt(self, id) {
                p
            } else {
                obj.power?
            }
        } else {
            obj.power?
        };

        // Continuous effects (auras, anthems, debuffs — including dynamic aura P/T).
        let (p_mod, _) = self.continuous_pt_mods(id, registry);
        power += p_mod;

        // +1/+1 and -1/-1 counter bonuses.
        power += *obj.counters.get(&crate::types::CounterType::PlusOnePlusOne).unwrap_or(&0) as i32;
        power -= *obj.counters.get(&crate::types::CounterType::MinusOneMinusOne).unwrap_or(&0) as i32;

        // Until-end-of-turn effects.
        for effect in &self.until_end_of_turn {
            match effect {
                TemporaryEffect::ModifyPT { target, power_mod, .. } if *target == id => {
                    power += power_mod;
                }
                TemporaryEffect::ModifyPTAll { controller, filter, power_mod, .. } => {
                    if obj.controller == *controller && obj.zone == Zone::Battlefield {
                        let matches = match filter {
                            None => true,
                            Some(f) => self.matches_filter(id, f, *controller, registry),
                        };
                        if matches { power += power_mod; }
                    }
                }
                TemporaryEffect::ModifyPTWhileSourceInPlay { target, source, power_mod, .. } if *target == id => {
                    if self.get_object(*source).map(|o| o.zone == Zone::Battlefield).unwrap_or(false) {
                        power += power_mod;
                    }
                }
                _ => {}
            }
        }

        Some(power)
    }

    /// Get the effective toughness of a creature.
    pub fn effective_toughness(&self, id: ObjectId, registry: &crate::cards::CardRegistry) -> Option<i32> {
        let obj = self.get_object(id)?;

        // Check if this token has dynamic P/T tied to counter count on a source permanent.
        let mut toughness = if let Some(source_id) = obj.card_state.get("pt_source_counter") {
            let counter_type_val = obj.card_state.get("pt_source_counter_type")
                .map(|v| v.0).unwrap_or(0);
            let counter_type = match counter_type_val {
                1 => crate::types::CounterType::Slime,
                _ => crate::types::CounterType::PlusOnePlusOne,
            };
            self.get_object(*source_id)
                .map(|src| *src.counters.get(&counter_type).unwrap_or(&0) as i32)
                .unwrap_or(0)
        } else if let Some(behavior) = registry.get(obj.card_id) {
            // Check if this creature's own card has dynamic P/T.
            if let Some((_, t)) = behavior.dynamic_pt(self, id) {
                t
            } else {
                obj.toughness?
            }
        } else {
            obj.toughness?
        };

        let (_, t_mod) = self.continuous_pt_mods(id, registry);
        toughness += t_mod;

        // +1/+1 and -1/-1 counter bonuses.
        toughness += *obj.counters.get(&crate::types::CounterType::PlusOnePlusOne).unwrap_or(&0) as i32;
        toughness -= *obj.counters.get(&crate::types::CounterType::MinusOneMinusOne).unwrap_or(&0) as i32;

        for effect in &self.until_end_of_turn {
            match effect {
                TemporaryEffect::ModifyPT { target, toughness_mod, .. } if *target == id => {
                    toughness += toughness_mod;
                }
                TemporaryEffect::ModifyPTAll { controller, filter, toughness_mod, .. } => {
                    if obj.controller == *controller && obj.zone == Zone::Battlefield {
                        let matches = match filter {
                            None => true,
                            Some(f) => self.matches_filter(id, f, *controller, registry),
                        };
                        if matches { toughness += toughness_mod; }
                    }
                }
                TemporaryEffect::ModifyPTWhileSourceInPlay { target, source, toughness_mod, .. } if *target == id => {
                    if self.get_object(*source).map(|o| o.zone == Zone::Battlefield).unwrap_or(false) {
                        toughness += toughness_mod;
                    }
                }
                _ => {}
            }
        }

        Some(toughness)
    }

    /// Check if a creature is prevented from attacking (e.g., by Pacifism).
    pub fn can_attack(&self, creature_id: ObjectId, registry: &crate::cards::CardRegistry) -> bool {
        if self.has_continuous_effect(creature_id, &|e| {
            use crate::types::ContinuousEffect;
            match e {
                ContinuousEffect::PreventAttack { scope } => Some(scope),
                _ => None,
            }
        }, registry) {
            return false;
        }
        // Check conditional prevent-attack (e.g., Bonds of Faith on non-Human).
        if self.has_conditional_prevent(creature_id, true, registry) {
            return false;
        }
        true
    }

    /// Check if a creature is prevented from blocking.
    pub fn can_block(&self, creature_id: ObjectId, registry: &crate::cards::CardRegistry) -> bool {
        if self.has_continuous_effect(creature_id, &|e| {
            use crate::types::ContinuousEffect;
            match e {
                ContinuousEffect::PreventBlock { scope } => Some(scope),
                _ => None,
            }
        }, registry) {
            return false;
        }
        // Check conditional prevent-block (e.g., Bonds of Faith on non-Human).
        if self.has_conditional_prevent(creature_id, false, registry) {
            return false;
        }
        true
    }

    /// Check if a creature on the battlefield has a given keyword ability.
    /// Checks static card keywords, continuous effect grants, aura grants, and until-EOT grants.
    pub fn has_keyword(&self, creature_id: ObjectId, keyword: crate::types::Keyword, registry: &crate::cards::CardRegistry) -> bool {
        let obj = match self.get_object(creature_id) {
            Some(o) if o.zone == Zone::Battlefield => o,
            _ => return false,
        };

        // Check if this keyword was temporarily removed until end of turn.
        if self.until_end_of_turn.iter().any(|e| matches!(e,
            TemporaryEffect::RemoveKeyword { target, keyword: kw }
            if *target == creature_id && *kw == keyword
        )) {
            return false;
        }

        // 1. Static keywords from card definition (or back face if transformed).
        // For cards with a registry entry the registry is authoritative — this
        // avoids returning stale front-face keywords after a transform that did
        // not go through helpers::apply_transform.
        if let Some(behavior) = registry.get(obj.card_id) {
            if obj.is_transformed {
                if let Some(back) = behavior.back_face_data() {
                    if back.keywords.contains(&keyword) {
                        return true;
                    }
                }
            } else if behavior.card_data().keywords.contains(&keyword) {
                return true;
            }
        } else {
            // 0. No registry entry (tokens, anonymous objects): fall back to
            //    keywords stored directly on the object.
            if obj.keywords.contains(&keyword) {
                return true;
            }
        }

        // 2. Keywords from continuous effects (auras with GrantKeyword, anthem keyword grants).
        let has_grant = self.has_continuous_effect(creature_id, &|e| {
            use crate::types::ContinuousEffect;
            match e {
                ContinuousEffect::GrantKeyword { keyword: kw, scope } if *kw == keyword => Some(scope),
                _ => None,
            }
        }, registry);
        if has_grant {
            return true;
        }

        // 2b. Conditional keywords (e.g., haste if opponent controls a Human).
        let has_conditional = self.has_conditional_keyword(creature_id, keyword, registry);
        if has_conditional {
            return true;
        }

        // 3. Temporary keyword grants (until end of turn).
        for effect in &self.until_end_of_turn {
            match effect {
                TemporaryEffect::GrantKeyword { target, keyword: kw } if *target == creature_id && *kw == keyword => {
                    return true;
                }
                TemporaryEffect::GrantKeywordAll { controller, filter, keyword: kw } if *kw == keyword => {
                    if let Some(obj) = self.get_object(creature_id) {
                        if obj.controller == *controller && obj.zone == Zone::Battlefield {
                            let matches = match filter {
                                None => true,
                                Some(f) => self.matches_filter(creature_id, f, *controller, registry),
                            };
                            if matches { return true; }
                        }
                    }
                }
                _ => {}
            }
        }

        false
    }

    /// Check if a creature has protection from a given source.
    /// Returns true if the target has protection from the source's subtypes or matches
    /// a ProtectionFrom filter. Used for targeting, blocking, and damage prevention.
    pub fn has_protection_from(&self, target_id: ObjectId, source_id: ObjectId, registry: &crate::cards::CardRegistry) -> bool {
        use crate::types::ContinuousEffect;

        // Get the source's subtypes.
        let source_subtypes: Vec<String> = self.get_object(source_id)
            .map(|o| {
                let mut subs = o.subtypes.clone();
                // Also get subtypes from registry.
                if let Some(data) = registry.card_data(o.card_id) {
                    for s in &data.subtypes {
                        if !subs.contains(s) {
                            subs.push(s.clone());
                        }
                    }
                }
                subs
            })
            .unwrap_or_default();

        // Check ProtectionFromSubtype effects on the target.
        let has_subtype_protection = self.has_continuous_effect(target_id, &|e| {
            match e {
                ContinuousEffect::ProtectionFromSubtype { subtype, scope } => {
                    if source_subtypes.iter().any(|s| s == subtype) {
                        Some(scope)
                    } else {
                        None
                    }
                }
                _ => None,
            }
        }, registry);
        if has_subtype_protection {
            return true;
        }

        // Check until-end-of-turn protection grants (e.g., Spare from Evil).
        for effect in &self.until_end_of_turn {
            match effect {
                TemporaryEffect::GrantProtection { target, filter } if *target == target_id => {
                    if self.matches_filter(source_id, filter, crate::ids::PlayerId(0), registry) {
                        return true;
                    }
                }
                TemporaryEffect::GrantProtectionAll { controller, protection_filter } => {
                    if let Some(obj) = self.get_object(target_id) {
                        if obj.controller == *controller && obj.zone == Zone::Battlefield {
                            if self.matches_filter(source_id, protection_filter, *controller, registry) {
                                return true;
                            }
                        }
                    }
                }
                _ => {}
            }
        }

        false
    }

    /// Check if a creature is prevented from attacking or blocking by a conditional effect.
    fn has_conditional_prevent(&self, creature_id: ObjectId, is_attack: bool, registry: &crate::cards::CardRegistry) -> bool {
        use crate::types::ContinuousEffect;
        for source in self.objects.values() {
            if source.zone != Zone::Battlefield {
                continue;
            }
            let effects = if let Some(ref instance_effects) = source.instance_continuous_effects {
                instance_effects.clone()
            } else if let Some(behavior) = registry.get(source.card_id) {
                if source.is_transformed {
                    behavior.back_face_data().map(|d| d.continuous_effects).unwrap_or_default()
                } else {
                    behavior.card_data().continuous_effects
                }
            } else {
                continue
            };
            for effect in &effects {
                let (condition, scope) = if is_attack {
                    match effect {
                        ContinuousEffect::ConditionalPreventAttack { condition, scope } => (condition, scope),
                        _ => continue,
                    }
                } else {
                    match effect {
                        ContinuousEffect::ConditionalPreventBlock { condition, scope } => (condition, scope),
                        _ => continue,
                    }
                };
                if self.effect_applies_to(creature_id, scope, source.id, source.controller, registry)
                    && self.check_condition(condition, source.id, source.controller, registry) {
                    return true;
                }
            }
        }
        false
    }

    /// Check if a creature has a conditional keyword that is currently active.
    fn has_conditional_keyword(&self, creature_id: ObjectId, keyword: crate::types::Keyword, registry: &crate::cards::CardRegistry) -> bool {
        use crate::types::ContinuousEffect;
        for source in self.objects.values() {
            if source.zone != Zone::Battlefield {
                continue;
            }
            let effects = if let Some(ref instance_effects) = source.instance_continuous_effects {
                instance_effects.clone()
            } else if let Some(behavior) = registry.get(source.card_id) {
                if source.is_transformed {
                    behavior.back_face_data().map(|d| d.continuous_effects).unwrap_or_default()
                } else {
                    behavior.card_data().continuous_effects
                }
            } else {
                continue;
            };
            for effect in &effects {
                if let ContinuousEffect::ConditionalKeyword { keyword: kw, condition, scope } = effect {
                    if *kw != keyword {
                        continue;
                    }
                    if !self.effect_applies_to(creature_id, scope, source.id, source.controller, registry) {
                        continue;
                    }
                    if self.check_condition(condition, source.id, source.controller, registry) {
                        return true;
                    }
                }
            }
        }
        false
    }

    /// Evaluate an EffectCondition for a given controller.
    fn check_condition(&self, condition: &crate::types::EffectCondition, source_id: ObjectId, controller: crate::ids::PlayerId, registry: &crate::cards::CardRegistry) -> bool {
        use crate::types::EffectCondition;
        match condition {
            EffectCondition::YouControlSubtype(subtype) => {
                self.objects.values().any(|o| {
                    o.zone == Zone::Battlefield && o.controller == controller && (
                        o.subtypes.iter().any(|s| s == subtype)
                        || registry.card_data(o.card_id)
                            .map(|d| d.subtypes.iter().any(|s| s == subtype))
                            .unwrap_or(false)
                    )
                })
            }
            EffectCondition::OpponentControlsSubtype(subtype) => {
                let opponent = self.opponent(controller);
                self.objects.values().any(|o| {
                    o.zone == Zone::Battlefield && o.controller == opponent && (
                        o.subtypes.iter().any(|s| s == subtype)
                        || registry.card_data(o.card_id)
                            .map(|d| d.subtypes.iter().any(|s| s == subtype))
                            .unwrap_or(false)
                    )
                })
            }
            EffectCondition::SelfHasKeyword(kw) => {
                let removed = self.until_end_of_turn.iter().any(|e| matches!(e,
                    TemporaryEffect::RemoveKeyword { target, keyword }
                    if *target == source_id && *keyword == *kw
                ));
                if removed {
                    return false;
                }
                self.get_object(source_id)
                    .map(|o| {
                        if o.keywords.contains(kw) {
                            true
                        } else {
                            registry.card_data(o.card_id)
                                .map(|d| d.keywords.contains(kw))
                                .unwrap_or(false)
                        }
                    })
                    .unwrap_or(false)
            }
            EffectCondition::AttachedHasSubtype(subtype) => {
                // Check if the creature this aura is attached to has the subtype.
                // Use obj.subtypes as authoritative when non-empty (covers type changes),
                // fall back to registry only when obj.subtypes is empty.
                self.get_object(source_id)
                    .and_then(|o| o.attached_to)
                    .and_then(|target_id| {
                        self.get_object(target_id).map(|target_obj| {
                            if !target_obj.subtypes.is_empty() {
                                target_obj.subtypes.iter().any(|s| s == subtype)
                            } else {
                                registry.card_data(target_obj.card_id)
                                    .map(|d| d.subtypes.iter().any(|s| s == subtype))
                                    .unwrap_or(false)
                            }
                        })
                    })
                    .unwrap_or(false)
            }
            EffectCondition::AttachedLacksSubtype(subtype) => {
                !self.check_condition(&EffectCondition::AttachedHasSubtype(subtype.clone()), source_id, controller, registry)
            }
        }
    }

    /// Move a resolving spell to the appropriate zone.
    /// Flashback spells go to exile; others go to graveyard.
    pub fn move_spell_after_resolve(&mut self, object_id: ObjectId, registry: &crate::cards::CardRegistry) {
        let exile = self.get_object(object_id)
            .map(|o| o.cast_with_flashback)
            .unwrap_or(false);
        if exile {
            self.move_object(object_id, Zone::Exile, registry);
        } else {
            self.move_object(object_id, Zone::Graveyard, registry);
        }
    }

    /// Check if a player has hexproof (e.g., from Witchbane Orb).
    pub fn player_has_hexproof(&self, player: PlayerId, registry: &crate::cards::CardRegistry) -> bool {
        self.objects.values().any(|o| {
            o.zone == Zone::Battlefield
                && o.controller == player
                && registry.get(o.card_id)
                    .map(|b| b.grants_player_hexproof())
                    .unwrap_or(false)
        })
    }

    /// Add counters to a permanent.
    pub fn add_counters(&mut self, id: ObjectId, counter_type: crate::types::CounterType, count: u32) {
        if let Some(obj) = self.objects.get_mut(&id) {
            *obj.counters.entry(counter_type).or_insert(0) += count;
        }
    }

    /// Get the number of counters of a type on a permanent.
    pub fn get_counter_count(&self, id: ObjectId, counter_type: crate::types::CounterType) -> u32 {
        self.get_object(id)
            .and_then(|o| o.counters.get(&counter_type))
            .copied()
            .unwrap_or(0)
    }

    /// Is the game over?
    pub fn is_game_over(&self) -> bool {
        self.result.is_some()
    }
}


/// A single game object — an instance of a card on the battlefield, in hand, etc.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GameObject {
    pub id: ObjectId,
    pub card_id: CardId,
    pub name: String,
    pub owner: PlayerId,
    pub controller: PlayerId,
    pub zone: Zone,

    // Battlefield state
    pub tapped: bool,
    pub summoning_sick: bool,
    pub damage_marked: u32,
    /// Which creatures have dealt damage to this creature this turn.
    /// Used by Abattoir Ghoul ("when creature dealt damage by this dies").
    #[serde(default)]
    pub damaged_by: Vec<ObjectId>,
    /// Whether this creature has been dealt damage by a source with deathtouch.
    pub dealt_deathtouch_damage: bool,

    // Characteristics (from card data, may be modified by effects later)
    pub power: Option<i32>,
    pub toughness: Option<i32>,
    pub colors: Vec<crate::types::Color>,
    /// Keywords on this object (populated from card_data for real cards, set directly for tokens).
    pub keywords: Vec<crate::types::Keyword>,
    /// Card types on this object (populated from card_data, set directly for tokens).
    pub card_types: Vec<crate::types::CardType>,
    /// Subtypes on this object (for tokens — regular cards use CardData.subtypes via registry).
    #[serde(default)]
    pub subtypes: Vec<String>,

    // Targets chosen when this spell was cast (only relevant while on the stack).
    pub targets: Vec<crate::actions::Target>,

    // Aura/equipment: what this is attached to.
    pub attached_to: Option<ObjectId>,
    // Curse aura: attached to a player (instead of an object).
    pub attached_to_player: Option<PlayerId>,

    // Tracks zone changes for staleness detection (XMage pattern).
    pub zone_change_count: u32,

    /// Whether this object is a token (tokens cease to exist when not on the battlefield).
    pub is_token: bool,
    /// Whether this permanent is legendary (for the legend rule SBA).
    #[serde(default)]
    pub is_legendary: bool,

    /// Whether this spell was cast using flashback (exiled instead of going to graveyard).
    #[serde(default)]
    pub cast_with_flashback: bool,

    /// Per-instance oracle text override (e.g., Bonds of Faith conditional effect).
    /// When set, aura parsing uses this instead of the card's static oracle text.
    #[serde(default)]
    pub instance_oracle_text: Option<String>,

    /// Per-instance continuous effects that override the card's static effects.
    /// Set by on_enter_battlefield for conditional cards (e.g., Bonds of Faith).
    #[serde(default)]
    pub instance_continuous_effects: Option<Vec<crate::types::ContinuousEffect>>,

    /// Card-specific persistent state (e.g., Fiend Hunter stores the exiled creature ID).
    /// Keyed by purpose string, value is an ObjectId.
    #[serde(default)]
    pub card_state: HashMap<String, ObjectId>,

    /// Counters on this permanent (+1/+1, -1/-1, etc.).
    pub counters: HashMap<crate::types::CounterType, u32>,

    /// Number of regeneration shields (consumed instead of destruction).
    #[serde(default)]
    pub regeneration_shields: u32,

    /// Whether this permanent is equipment (stays on battlefield when unattached).
    #[serde(default)]
    pub is_equipment: bool,

    /// Whether this double-faced card is on its back face.
    #[serde(default)]
    pub is_transformed: bool,

    /// Whether a state-triggered ability (CR 603.8) for this object is currently
    /// on the stack. While true, the trigger won't fire again.
    #[serde(default)]
    pub state_trigger_on_stack: bool,

    /// Chosen X value for X-cost spells (stored while on the stack).
    #[serde(default)]
    pub x_value: Option<u32>,

    /// Chosen mode index for ModalChoice spells (stored while on the stack).
    /// Set when a spell with a ModalChoice target requirement is cast.
    #[serde(default)]
    pub chosen_mode: Option<usize>,

    /// Activated abilities used this turn (for once-per-turn tracking).
    #[serde(default)]
    pub abilities_activated_this_turn: std::collections::HashSet<usize>,

    /// Whether this permanent is an entering-battlefield copy source (replacement effect).
    /// When true, other creatures entering the battlefield under the same controller
    /// enter as a copy of this permanent instead of their original form (CR 614.1d).
    /// Used by Essence of the Wild and similar cards.
    #[serde(default)]
    pub entering_copy_source: bool,
}

/// A player's state.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlayerState {
    pub id: PlayerId,
    pub life: i32,
    pub mana_pool: ManaPool,
    pub land_plays_remaining: u32,
    pub lost: bool,
    pub has_drawn_from_empty: bool,
    /// Order of cards in library (first element is top of library).
    pub library_order: Vec<ObjectId>,
    /// Number of mulligans this player has taken during the opening-hand phase.
    /// Used to determine how many cards must be bottomed after keeping.
    #[serde(default)]
    pub mulligan_count: u32,
    /// True once this player has chosen `MulliganKeep` (or hit the cap).
    /// Players with `mulligan_kept = true` are skipped in subsequent
    /// mulligan rounds.
    #[serde(default)]
    pub mulligan_kept: bool,
}

impl PlayerState {
    pub fn new(id: PlayerId) -> Self {
        Self {
            id,
            life: 40, // commander starting life
            mana_pool: ManaPool::new(),
            land_plays_remaining: 1,
            lost: false,
            has_drawn_from_empty: false,
            library_order: Vec::new(),
            mulligan_count: 0,
            mulligan_kept: false,
        }
    }

    /// Draw the top card of the library. Returns None if library is empty.
    pub fn draw_top_card(&mut self) -> Option<ObjectId> {
        if self.library_order.is_empty() {
            self.has_drawn_from_empty = true;
            None
        } else {
            Some(self.library_order.remove(0))
        }
    }

    /// Remove the top card from the library without setting has_drawn_from_empty.
    /// Used for reveal/search loops that are NOT drawing (e.g., Mirror-Mad Phantasm).
    pub fn reveal_top_card(&mut self) -> Option<ObjectId> {
        if self.library_order.is_empty() {
            None
        } else {
            Some(self.library_order.remove(0))
        }
    }
}

/// Combat state, tracking attackers and blockers.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CombatState {
    /// Map of attacker ObjectId -> defending PlayerId.
    pub attackers: HashMap<ObjectId, PlayerId>,
    /// Map of attacker ObjectId -> list of blockers assigned to it.
    pub blocker_assignments: HashMap<ObjectId, Vec<ObjectId>>,
}

impl CombatState {
    pub fn new() -> Self {
        Self {
            attackers: HashMap::new(),
            blocker_assignments: HashMap::new(),
        }
    }
}

/// What the engine is waiting for the player to do.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum AwaitingAction {
    DeclareAttackers,
    DeclareBlockers { defending_player: PlayerId },
    DiscardToHandSize { player: PlayerId, discard_count: usize },
    /// A card or trigger needs a player to make a choice during resolution.
    ResolutionChoice {
        player: PlayerId,
        source: ObjectId,
        choice: ResolutionChoiceKind,
    },
    /// London mulligan: `player` must decide keep or mull.
    MulliganDecision { player: PlayerId },
    /// London mulligan: `player` must put `count` cards on the bottom of
    /// their library (one per mulligan taken).
    BottomAfterMulligan { player: PlayerId, count: usize },
}

/// London mulligan cap: house rule, stop offering mulligans once a player
/// has taken this many. (Mull-to-4: after 3 mulligans you must keep.)
pub const LONDON_MULLIGAN_CAP: u32 = 3;

/// Describes what kind of mid-resolution choice is needed.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ResolutionChoiceKind {
    /// Choose whether to pay a cost (Frightful Delusion's "pay {1}").
    PayOrNot {
        description: String,
        spell_id: ObjectId,
        source_spell_id: ObjectId,
    },
    /// Choose one target from a list (damage, destroy, return, counters).
    ChooseTarget {
        description: String,
        options: Vec<crate::actions::Target>,
        optional: bool,
        effect: PendingEffect,
    },
    /// A yes/no choice ("you may" abilities).
    /// If yes, the card's trigger continues with its effect.
    /// If no, nothing happens.
    YesNo {
        description: String,
        source_card: ObjectId,
    },
    /// Choose a card from hand to discard (Murder of Crows, future discard effects).
    ChooseCardFromHand {
        description: String,
        player: PlayerId,
        cards: Vec<ObjectId>,
    },
    /// Choose one card from a revealed set to keep (Forbidden Alchemy).
    ChooseFromRevealed {
        description: String,
        revealed: Vec<ObjectId>,
        spell_id: ObjectId,
    },
    /// Search library for a card matching criteria and choose one (Garruk -1, etc.).
    /// All matching cards are shown to the player. They pick one to put into hand.
    /// After choosing, the library is shuffled.
    ChooseFromLibrary {
        description: String,
        /// All cards in the library that match the search criteria.
        options: Vec<ObjectId>,
        /// The player whose library is being searched.
        searcher: PlayerId,
        /// The source permanent that initiated the search.
        source_id: ObjectId,
    },
    /// Choose a permanent type from a list of options (Creeping Renaissance).
    ChooseCardType {
        description: String,
        options: Vec<String>,
        spell_id: ObjectId,
        controller: PlayerId,
    },
    /// Divide permanents into two piles (Liliana of the Veil -6).
    /// The choosing player selects a subset to form pile 1; the rest form pile 2.
    /// After division, the target player chooses which pile to sacrifice.
    DividePermanentsIntoPiles {
        description: String,
        /// All permanents to divide.
        permanents: Vec<ObjectId>,
        /// The player who will choose which pile to sacrifice (the target player).
        target_player: PlayerId,
        /// The source permanent (Liliana).
        source_id: ObjectId,
    },
    /// Choose one of two piles to sacrifice (Liliana of the Veil -6, step 2).
    ChoosePile {
        description: String,
        /// Permanents in pile 1.
        pile_1: Vec<ObjectId>,
        /// Permanents in pile 2.
        pile_2: Vec<ObjectId>,
        /// The source permanent (Liliana).
        source_id: ObjectId,
    },
    /// Choose a card name from all implemented nonland cards (Nevermore).
    ChooseCardName {
        description: String,
        /// All valid card names the player can choose from.
        options: Vec<String>,
        /// The source permanent that needs the chosen name.
        source_id: ObjectId,
    },
    /// Choose X for an X-cost spell or activated ability.
    /// The player picks a value from 0..=max_x, then that much mana is
    /// drained from the pool and stored on the spell/ability.
    ChooseXValue {
        description: String,
        /// Maximum X the player can afford.
        max_x: u32,
        /// The spell on the stack (for spells) or the source permanent (for abilities).
        source_id: ObjectId,
        /// True if this is for an activated ability (uses last_activated_x_value),
        /// false for a spell (uses obj.x_value on the stack object).
        is_ability: bool,
    },
}

/// What happens to the chosen target when a ResolutionChoice is resolved.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum PendingEffect {
    /// Deal N damage to the chosen target.
    DealDamage { amount: u32, source_id: ObjectId, source_name: String },
    /// Destroy the chosen permanent.
    Destroy { source_name: String },
    /// Move chosen creature from graveyard to battlefield.
    ReturnToBattlefield { spell_id: ObjectId },
    /// Put +1/+1 counters on chosen creature.
    AddCounters { count: u32, human_bonus: bool },
    /// Apply -N/-M until end of turn to the chosen creature.
    DebuffUntilEOT { power: i32, toughness: i32, source_name: String },
    /// Target creature can't block this turn.
    CantBlockThisTurn { source_name: String },
    /// Target player mills N cards.
    Mill { count: u32, source_name: String },
    /// Exile the chosen creature and store its ID on the source permanent.
    ExileAndStore { source_id: ObjectId, source_name: String },
    /// Target player draws a card and loses 1 life (Bloodgift Demon).
    DrawAndLoseLife { source_name: String },
    /// Destroy target creature matching a filter (Reaper from the Abyss).
    DestroyCreature { source_name: String },
    /// Exile the chosen card from graveyard (Curse of Oblivion).
    /// If remaining > 0, presents another exile choice after this one.
    ExileCurseOfOblivion { remaining: u32 },
    /// Return the chosen object to its owner's hand.
    ReturnToHand { source_name: String },
    /// Put the chosen object on top of its owner's library.
    PutOnTopOfLibrary { source_name: String },
    /// Sacrifice the chosen creature and gain life equal to its toughness (Tribute to Hunger).
    /// `beneficiary` gains the life; `spell_id` is cleaned up after resolution.
    SacrificeAndGainLife { beneficiary: PlayerId, spell_id: ObjectId },
    /// Exile a card from graveyard; if it's a creature card, controller gains 2 life (Graveyard Shovel).
    ExileFromGraveyardGainLife { controller: PlayerId },
    /// Sacrifice the chosen creature, then search library for a creature card (Garruk -1).
    SacrificeAndTutor { garruk_id: ObjectId },
    /// Destroy the target creature, then put a +1/+1 counter on the source permanent.
    /// The counter is added regardless of whether destruction succeeds (indestructible/regenerate),
    /// but the entire effect is skipped if the target is illegal.
    DestroyThenCounter { source_id: ObjectId, source_name: String },
    /// Sacrifice the chosen creature (generic sacrifice, e.g. Liliana -2).
    SacrificeCreature { source_name: String },
    /// Copy the chosen creature onto the source permanent (Evil Twin clone effect).
    /// The source becomes a copy of the target, except it retains any extra abilities
    /// stored via card_state markers.
    CopyCreature { source_id: ObjectId },
    /// "Each player chooses a creature they control. Destroy the rest."
    /// The chosen creature is added to `kept_so_far`. If `remaining_players` is non-empty,
    /// the next player's choice is presented. Once all players have chosen, all creatures
    /// on the battlefield that aren't in the kept set are destroyed.
    KeepOneDestroyRest {
        /// Players still needing to choose (in turn order), after the current chooser.
        remaining_players: Vec<PlayerId>,
        /// Creatures already chosen to keep by earlier players.
        kept_so_far: Vec<ObjectId>,
        /// The spell that initiated this effect (for logging).
        source_name: String,
    },
    /// Attach a Curse card from library onto the battlefield attached to the chosen player
    /// (Bitterheart Witch). The curse_id is the library object to move; searcher is the
    /// controller whose library is shuffled afterwards.
    AttachCurseToPlayer { curse_id: ObjectId, searcher: PlayerId },
    /// Two-step Curse selection: player chose a Curse from library, now need to choose a player.
    ChooseCurseThenAttach { searcher: PlayerId, source: ObjectId },
    /// Grant flashback to a chosen card until end of turn (Snapcaster Mage).
    GrantFlashback { source_name: String },
    /// Target player loses 1 life, controller gains 1 life (Falkenrath Noble, etc.).
    DrainLife { controller: PlayerId, source_name: String },
    /// Put the chosen basic land from library onto the battlefield, then shuffle (Ghost Quarter).
    GhostQuarterSearch { searcher: PlayerId },
    /// Exile the chosen card (from hand) and move the source spell to the graveyard (Night Terrors).
    ExileCardAndCleanup { spell_id: ObjectId, source_name: String },
    /// Exile the chosen creature card from graveyard and create a Spirit token (Moorland Haunt).
    ExileFromGraveyardAndCreateToken { controller: PlayerId },
    /// The legend rule: the chosen permanent is KEPT, all others with the same name
    /// under that player's control are sent to the graveyard.
    LegendRuleKeep { player: PlayerId, legend_name: String },
}

/// Game result.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum GameResult {
    Winner(PlayerId),
    Draw,
}

/// Day/night state for werewolf transform tracking.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum DayNight {
    Day,
    Night,
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ids::CardId;

    #[test]
    fn create_and_move_object() {
        let registry = crate::cards::CardRegistry::with_all_cards();
        let mut state = GameState::new(2);
        let id = state.create_object(CardId(1), PlayerId(0), Zone::Hand, None, None);

        assert_eq!(state.get_object(id).unwrap().zone, Zone::Hand);

        state.move_object(id, Zone::Battlefield, &registry);
        let obj = state.get_object(id).unwrap();
        assert_eq!(obj.zone, Zone::Battlefield);
        assert!(obj.summoning_sick);
        assert_eq!(obj.zone_change_count, 1);
    }

    #[test]
    fn objects_in_zone_filters_correctly() {
        let mut state = GameState::new(2);
        let p0 = PlayerId(0);
        let p1 = PlayerId(1);

        state.create_object(CardId(1), p0, Zone::Hand, None, None);
        state.create_object(CardId(2), p0, Zone::Hand, None, None);
        state.create_object(CardId(1), p1, Zone::Hand, None, None);

        assert_eq!(state.objects_in_zone(Zone::Hand, p0).len(), 2);
        assert_eq!(state.objects_in_zone(Zone::Hand, p1).len(), 1);
    }

    #[test]
    fn leaving_battlefield_resets_state() {
        let registry = crate::cards::CardRegistry::with_all_cards();
        let mut state = GameState::new(2);
        let id = state.create_object(CardId(1), PlayerId(0), Zone::Battlefield, Some(2), Some(2));

        {
            let obj = state.get_object_mut(id).unwrap();
            obj.tapped = true;
            obj.damage_marked = 1;
        }

        state.move_object(id, Zone::Graveyard, &registry);
        let obj = state.get_object(id).unwrap();
        assert!(!obj.tapped);
        assert_eq!(obj.damage_marked, 0);
        assert!(!obj.summoning_sick);
    }

    #[test]
    fn draw_from_empty_library() {
        let mut state = GameState::new(2);
        let player = state.get_player_mut(PlayerId(0));
        assert!(player.draw_top_card().is_none());
        assert!(player.has_drawn_from_empty);
    }
}
