use std::collections::HashMap;

use serde::{Serialize, Deserialize};

use crate::ids::{ObjectId, PlayerId, CardId};
use crate::types::{Zone, Step, ManaPool, ManaCost};

/// An entry on the stack — either a spell or a triggered ability.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum StackEntry {
    /// A spell (instant, sorcery, creature, etc.) on the stack.
    Spell(ObjectId),
    /// A triggered ability on the stack. Resolves by calling the card behavior.
    Trigger(crate::triggers::PendingTrigger),
}

impl StackEntry {
    /// Get the ObjectId if this is a spell.
    pub fn as_spell(&self) -> Option<ObjectId> {
        match self {
            StackEntry::Spell(id) => Some(*id),
            StackEntry::Trigger(_) => None,
        }
    }

    /// Get the trigger if this is a triggered ability.
    pub fn as_trigger(&self) -> Option<&crate::triggers::PendingTrigger> {
        match self {
            StackEntry::Trigger(t) => Some(t),
            StackEntry::Spell(_) => None,
        }
    }

    /// Description for display purposes.
    pub fn display_name(&self, registry: &crate::cards::CardRegistry) -> String {
        match self {
            StackEntry::Spell(id) => format!("Spell({})", id.0),
            StackEntry::Trigger(t) => t.display_name(registry),
        }
    }
}

/// The complete, immutable game state. Clone to produce new states.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GameState {
    /// All game objects keyed by their unique ID.
    pub objects: HashMap<ObjectId, GameObject>,
    /// Monotonic counter for generating unique ObjectIds.
    pub next_object_id: u64,

    /// Player states, indexed by PlayerId.0.
    pub players: Vec<PlayerState>,

    /// Turn structure.
    pub turn_number: u32,
    pub active_player: PlayerId,
    pub priority_player: Option<PlayerId>,
    pub step: Step,

    /// The stack. Last element is top of stack. Contains spells and triggered abilities.
    pub stack: Vec<StackEntry>,

    /// Combat state, present only during combat phase.
    pub combat: Option<CombatState>,

    /// Whether the game is waiting for attackers/blockers declaration.
    pub awaiting_action: Option<AwaitingAction>,

    /// Game result, if the game is over.
    pub result: Option<GameResult>,

    /// Number of consecutive priority passes (resets on any non-pass action).
    pub consecutive_passes: u32,

    /// Whether this is the very first turn of the game (skip draw step).
    pub is_first_turn: bool,

    /// Events generated by the most recent action.
    pub events: Vec<crate::events::GameEvent>,

    /// Game log with levels. File gets everything, UI filters by level.
    pub game_log: Vec<LogEntry>,

    /// Temporary effects that expire at end of turn (e.g., Giant Growth's +3/+3).
    pub until_end_of_turn_effects: Vec<UntilEndOfTurnEffect>,

    /// Temporary keyword grants that expire at end of turn.
    pub until_end_of_turn_keywords: Vec<UntilEndOfTurnKeyword>,

    /// Temporary "can't block" restrictions that expire at end of turn.
    pub until_end_of_turn_cant_block: Vec<ObjectId>,

    /// Temporary protection grants that expire at end of turn.
    /// Each entry grants a creature protection from creatures matching a filter.
    #[serde(default)]
    pub until_end_of_turn_protection: Vec<UntilEndOfTurnProtection>,

    /// Keywords temporarily removed until end of turn (e.g., Manor Gargoyle loses defender).
    /// At cleanup, these keywords are restored on their objects.
    #[serde(default)]
    pub until_end_of_turn_removed_keywords: Vec<UntilEndOfTurnKeyword>,

    /// Temporary control changes that revert at end of turn.
    /// Each entry is (object_id, original_controller).
    #[serde(default)]
    pub until_end_of_turn_control_changes: Vec<(ObjectId, PlayerId)>,

    /// Temporary flashback grants that expire at end of turn.
    /// Each entry is (object_id, flashback_cost).
    #[serde(default)]
    pub until_end_of_turn_flashback: Vec<(ObjectId, ManaCost)>,

    /// Whether a creature has died this turn (for morbid).
    #[serde(default)]
    pub creature_died_this_turn: bool,

    /// Day/night state for werewolf transform tracking.
    #[serde(default)]
    pub day_night: Option<DayNight>,

    /// Number of spells cast this turn by each player (for werewolf transforms).
    #[serde(default)]
    pub spells_cast_this_turn: HashMap<PlayerId, u32>,

    /// Spells cast last turn (saved at turn start for werewolf condition checking).
    #[serde(default)]
    pub spells_cast_last_turn: HashMap<PlayerId, u32>,

    /// Index for trigger processing resumption after a resolution choice.
    #[serde(default)]
    pub trigger_event_index: usize,

    /// Pending triggered abilities waiting to resolve, in APNAP order.
    /// Active player's triggers at the front (bottom of "stack"),
    /// non-active player's at the back (top). Resolved LIFO from the back.
    #[serde(default)]
    pub pending_triggers: Vec<crate::triggers::PendingTrigger>,
}

/// Log level for game log entries.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum LogLevel {
    /// Every priority pass, mana tap, etc.
    Debug = 0,
    /// Actions taken: land plays, phase changes.
    Info = 1,
    /// Important game events: spells cast/resolved, combat, life changes.
    Event = 2,
    /// Major game moments: turn changes, player death, game over.
    Milestone = 3,
}

/// A single log entry with a level.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LogEntry {
    pub level: LogLevel,
    pub message: String,
}

/// A temporary modifier applied to an object that expires at cleanup.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UntilEndOfTurnEffect {
    pub target: ObjectId,
    pub power_mod: i32,
    pub toughness_mod: i32,
}

/// A temporary keyword grant that expires at cleanup.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UntilEndOfTurnKeyword {
    pub target: ObjectId,
    pub keyword: crate::types::Keyword,
}

/// A temporary protection grant that expires at cleanup.
/// Grants protection from creatures matching a filter.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UntilEndOfTurnProtection {
    pub target: ObjectId,
    pub filter: crate::types::CreatureFilter,
}

impl GameState {
    /// Create a new game state for a given number of players.
    pub fn new(num_players: u8) -> Self {
        let players = (0..num_players)
            .map(|i| PlayerState::new(PlayerId(i)))
            .collect();

        Self {
            objects: HashMap::new(),
            next_object_id: 1,
            players,
            turn_number: 1,
            active_player: PlayerId(0),
            priority_player: None,
            step: Step::Untap,
            stack: Vec::new(),
            combat: None,
            awaiting_action: None,
            result: None,
            consecutive_passes: 0,
            is_first_turn: true,
            events: Vec::new(),
            game_log: Vec::new(),
            until_end_of_turn_effects: Vec::new(),
            until_end_of_turn_keywords: Vec::new(),
            until_end_of_turn_cant_block: Vec::new(),
            until_end_of_turn_protection: Vec::new(),
            until_end_of_turn_removed_keywords: Vec::new(),
            until_end_of_turn_control_changes: Vec::new(),
            until_end_of_turn_flashback: Vec::new(),
            creature_died_this_turn: false,
            day_night: None,
            spells_cast_this_turn: HashMap::new(),
            spells_cast_last_turn: HashMap::new(),
            trigger_event_index: 0,
            pending_triggers: Vec::new(),
        }
    }

    /// Allocate a fresh ObjectId.
    pub fn next_id(&mut self) -> ObjectId {
        let id = ObjectId(self.next_object_id);
        self.next_object_id += 1;
        id
    }

    /// Create a new game object and add it to the state.
    pub fn create_object(
        &mut self,
        card_id: CardId,
        owner: PlayerId,
        zone: Zone,
        power: Option<i32>,
        toughness: Option<i32>,
    ) -> ObjectId {
        let id = self.next_id();
        let obj = GameObject {
            id,
            card_id,
            name: String::new(), // Set by caller or setup_game
            owner,
            controller: owner,
            zone,
            tapped: false,
            summoning_sick: zone == Zone::Battlefield,
            damage_marked: 0,
            dealt_deathtouch_damage: false, damaged_by: Vec::new(),
            power,
            toughness,
            colors: Vec::new(),
            keywords: Vec::new(),
            card_types: Vec::new(),
            subtypes: Vec::new(),
            targets: Vec::new(),
            attached_to: None,
            attached_to_player: None,
            zone_change_count: 0,
            is_token: false,
            is_legendary: false,
            cast_with_flashback: false,
            instance_oracle_text: None,
            instance_continuous_effects: None,
            card_state: HashMap::new(),
            counters: HashMap::new(),
            regeneration_shields: 0,
            is_equipment: false,
            is_transformed: false,
            x_value: None,
            abilities_activated_this_turn: std::collections::HashSet::new(),
        };
        self.objects.insert(id, obj);
        id
    }

    /// Create a token on the battlefield.
    pub fn create_token(
        &mut self,
        name: &str,
        owner: PlayerId,
        power: i32,
        toughness: i32,
        colors: Vec<crate::types::Color>,
        card_types: Vec<crate::types::CardType>,
        keywords: Vec<crate::types::Keyword>,
    ) -> ObjectId {
        self.create_token_with_subtypes(name, owner, power, toughness, colors, card_types, keywords, vec![])
    }

    /// Create a token on the battlefield with specific creature subtypes.
    /// If Parallel Lives is on the battlefield under the same controller,
    /// an additional copy of the token is created.
    pub fn create_token_with_subtypes(
        &mut self,
        name: &str,
        owner: PlayerId,
        power: i32,
        toughness: i32,
        colors: Vec<crate::types::Color>,
        card_types: Vec<crate::types::CardType>,
        keywords: Vec<crate::types::Keyword>,
        subtypes: Vec<String>,
    ) -> ObjectId {
        // Check for Parallel Lives (doubling effect).
        let parallel_lives_count = self.objects.values()
            .filter(|o| o.zone == Zone::Battlefield && o.controller == owner && o.name == "Parallel Lives")
            .count();
        // Each Parallel Lives doubles, so 1 PL = 2x, 2 PL = 4x, etc.
        // We create (2^N - 1) extra tokens.
        let extra_copies = if parallel_lives_count > 0 {
            (1u32 << parallel_lives_count) - 1
        } else {
            0
        };

        // Create the primary token.
        let id = self.create_token_internal(name, owner, power, toughness,
            colors.clone(), card_types.clone(), keywords.clone(), subtypes.clone());

        // Create extra copies for Parallel Lives.
        for _ in 0..extra_copies {
            self.create_token_internal(name, owner, power, toughness,
                colors.clone(), card_types.clone(), keywords.clone(), subtypes.clone());
        }

        id
    }

    /// Internal token creation without Parallel Lives doubling.
    fn create_token_internal(
        &mut self,
        name: &str,
        owner: PlayerId,
        power: i32,
        toughness: i32,
        colors: Vec<crate::types::Color>,
        card_types: Vec<crate::types::CardType>,
        keywords: Vec<crate::types::Keyword>,
        subtypes: Vec<String>,
    ) -> ObjectId {
        let id = self.next_id();
        let obj = GameObject {
            id,
            card_id: CardId(0), // sentinel for tokens
            name: name.to_string(),
            owner,
            controller: owner,
            zone: Zone::Battlefield,
            tapped: false,
            summoning_sick: true,
            damage_marked: 0,
            dealt_deathtouch_damage: false, damaged_by: Vec::new(),
            power: Some(power),
            toughness: Some(toughness),
            colors,
            keywords,
            card_types,
            subtypes,
            targets: Vec::new(),
            attached_to: None,
            attached_to_player: None,
            zone_change_count: 0,
            is_token: true,
            is_legendary: false,
            cast_with_flashback: false,
            instance_oracle_text: None,
            instance_continuous_effects: None,
            card_state: HashMap::new(),
            counters: HashMap::new(),
            regeneration_shields: 0,
            is_equipment: false,
            is_transformed: false,
            x_value: None,
            abilities_activated_this_turn: std::collections::HashSet::new(),
        };
        self.objects.insert(id, obj);
        self.events.push(crate::events::GameEvent::EnteredBattlefield {
            object: id,
            controller: owner,
        });
        id
    }

    /// Create a token that copies all characteristics of a source permanent.
    /// Used by Cackling Counterpart, Evil Twin, etc.
    pub fn create_token_copy(
        &mut self,
        source_id: ObjectId,
        owner: PlayerId,
        registry: &crate::cards::CardRegistry,
    ) -> ObjectId {
        let source = self.get_object(source_id);
        let (name, power, toughness, card_id) = match source {
            Some(o) => (o.name.clone(), o.power, o.toughness, o.card_id),
            None => return ObjectId(0),
        };
        let (colors, keywords, card_types, subtypes) = registry.card_data(card_id)
            .map(|d| (
                Vec::new(), // colors TODO
                d.keywords.clone(),
                d.card_types.clone(),
                d.subtypes.clone(),
            ))
            .unwrap_or_default();

        let id = self.create_token_with_subtypes(
            &name,
            owner,
            power.unwrap_or(0),
            toughness.unwrap_or(0),
            colors,
            card_types,
            keywords,
            subtypes.iter().map(|s| s.to_string()).collect(),
        );
        // Copy the card_id so the token gets the same CardBehavior.
        if let Some(obj) = self.get_object_mut(id) {
            obj.card_id = card_id;
        }
        id
    }

    /// Move an object to a new zone.
    /// Per MTG rules, changing zones makes it a "new object" — we increment zone_change_count.
    pub fn move_object(&mut self, id: ObjectId, to: Zone) {
        // Collect log info before mutating.
        let log_msg = self.objects.get(&id).and_then(|obj| {
            if obj.zone == Zone::Battlefield && to != Zone::Battlefield && obj.power.is_some() {
                let dest = match to {
                    Zone::Graveyard => "died",
                    Zone::Exile => "was exiled",
                    _ => "left the battlefield",
                };
                Some(format!("{} {}", obj.name, dest))
            } else {
                None
            }
        });

        if let Some(msg) = log_msg {
            self.log(LogLevel::Event, msg);
        }

        let from = self.objects.get(&id).map(|o| o.zone);

        if let Some(obj) = self.objects.get_mut(&id) {
            let from = obj.zone;
            obj.zone = to;
            obj.zone_change_count += 1;

            // Reset battlefield-specific state when leaving the battlefield.
            if from == Zone::Battlefield && to != Zone::Battlefield {
                obj.tapped = false;
                obj.summoning_sick = false;
                obj.damage_marked = 0;
                obj.dealt_deathtouch_damage = false; obj.damaged_by.clear();
                obj.attached_to = None;
                obj.counters.clear();
                obj.regeneration_shields = 0;
            }

            // Set summoning sickness when entering the battlefield.
            if to == Zone::Battlefield && from != Zone::Battlefield {
                obj.summoning_sick = true;
            }
        }

        // Emit zone-change events outside the mutable borrow.
        if let Some(from_zone) = from {
            if from_zone == Zone::Battlefield && to != Zone::Battlefield {
                self.events.push(crate::events::GameEvent::LeftBattlefield {
                    object: id,
                    to,
                });
            }
            if to == Zone::Battlefield && from_zone != Zone::Battlefield {
                let controller = self.get_object(id).map(|o| o.controller).unwrap_or(PlayerId(0));
                self.events.push(crate::events::GameEvent::EnteredBattlefield {
                    object: id,
                    controller,
                });
            }
        }
    }

    /// Get an object by ID.
    pub fn get_object(&self, id: ObjectId) -> Option<&GameObject> {
        self.objects.get(&id)
    }

    /// Get a mutable reference to an object by ID.
    pub fn get_object_mut(&mut self, id: ObjectId) -> Option<&mut GameObject> {
        self.objects.get_mut(&id)
    }

    /// Get a player by ID.
    pub fn get_player(&self, id: PlayerId) -> &PlayerState {
        &self.players[id.0 as usize]
    }

    /// Get a mutable reference to a player by ID.
    pub fn get_player_mut(&mut self, id: PlayerId) -> &mut PlayerState {
        &mut self.players[id.0 as usize]
    }

    /// Get all objects in a zone owned/controlled by a player.
    /// For Library/Hand/Graveyard: filter by owner (per rule 400.3).
    /// For Battlefield: filter by controller.
    pub fn objects_in_zone(&self, zone: Zone, player: PlayerId) -> Vec<&GameObject> {
        self.objects.values().filter(|obj| {
            obj.zone == zone && match zone {
                Zone::Library | Zone::Hand | Zone::Graveyard => obj.owner == player,
                Zone::Battlefield => obj.controller == player,
                _ => true,
            }
        }).collect()
    }

    /// Get all objects in a zone (regardless of player).
    pub fn all_objects_in_zone(&self, zone: Zone) -> Vec<&GameObject> {
        self.objects.values().filter(|obj| obj.zone == zone).collect()
    }

    /// Get the next player after the given player (turn order).
    pub fn next_player(&self, player: PlayerId) -> PlayerId {
        let next = (player.0 + 1) % self.players.len() as u8;
        PlayerId(next)
    }

    /// Get the opponent in a 2-player game.
    pub fn opponent(&self, player: PlayerId) -> PlayerId {
        self.next_player(player)
    }

    /// Number of alive players.
    pub fn alive_player_count(&self) -> usize {
        self.players.iter().filter(|p| !p.lost).count()
    }

    /// Add a log entry.
    pub fn log(&mut self, level: LogLevel, msg: String) {
        self.game_log.push(LogEntry { level, message: msg });
    }

    /// Check if a creature matches a CreatureFilter, evaluated from the perspective
    /// of the effect's source permanent.
    pub fn matches_filter(
        &self,
        creature_id: ObjectId,
        filter: &crate::types::CreatureFilter,
        source_controller: PlayerId,
        registry: &crate::cards::CardRegistry,
    ) -> bool {
        use crate::types::CreatureFilter;
        let creature = match self.get_object(creature_id) {
            Some(o) => o,
            None => return false,
        };
        match filter {
            CreatureFilter::You => creature.controller == source_controller,
            CreatureFilter::Opponents => creature.controller != source_controller,
            CreatureFilter::YourTokens => creature.controller == source_controller && creature.is_token,
            CreatureFilter::HasSubtype(subtype) => {
                // For transformed DFCs, use back face subtypes instead of front face.
                if creature.is_transformed {
                    if let Some(behavior) = registry.get(creature.card_id) {
                        if let Some(back) = behavior.back_face_data() {
                            if back.subtypes.iter().any(|s| s == subtype) {
                                return true;
                            }
                        }
                    }
                } else {
                    // Check card data subtypes first, then object-level subtypes (for tokens).
                    if registry.card_data(creature.card_id)
                        .map(|d| d.subtypes.iter().any(|s| s == subtype))
                        .unwrap_or(false) {
                        return true;
                    }
                }
                creature.subtypes.iter().any(|s| s == subtype)
            }
            CreatureFilter::HasKeyword(kw) => self.has_keyword(creature_id, *kw, registry),
            CreatureFilter::And(filters) => filters.iter().all(|f| self.matches_filter(creature_id, f, source_controller, registry)),
            CreatureFilter::Or(filters) => filters.iter().any(|f| self.matches_filter(creature_id, f, source_controller, registry)),
            CreatureFilter::Not(inner) => !self.matches_filter(creature_id, inner, source_controller, registry),
            CreatureFilter::AttachedPlayer => {
                // This filter requires knowing the source object's attached_to_player.
                // It's resolved in effect_applies_to which has source_id.
                // If called directly from matches_filter without source context,
                // fall back to Opponents (the common case for curses).
                creature.controller != source_controller
            }
        }
    }

    /// Check if a continuous effect applies to a given creature.
    pub fn effect_applies_to(
        &self,
        creature_id: ObjectId,
        scope: &crate::types::EffectScope,
        source_id: ObjectId,
        source_controller: PlayerId,
        registry: &crate::cards::CardRegistry,
    ) -> bool {
        use crate::types::EffectScope;
        match scope {
            EffectScope::OnSelf => creature_id == source_id,
            EffectScope::Attached => {
                self.get_object(source_id)
                    .and_then(|o| o.attached_to)
                    .map(|target| target == creature_id)
                    .unwrap_or(false)
            }
            EffectScope::Global(filter) => {
                // For AttachedPlayer filter, use the source's attached_to_player.
                if matches!(filter, crate::types::CreatureFilter::AttachedPlayer) {
                    let attached_player = self.get_object(source_id)
                        .and_then(|o| o.attached_to_player);
                    if let Some(player) = attached_player {
                        let creature = self.get_object(creature_id);
                        return creature.map(|c| c.controller == player).unwrap_or(false);
                    }
                    return false;
                }
                self.matches_filter(creature_id, filter, source_controller, registry)
            }
            EffectScope::GlobalOther(filter) => {
                creature_id != source_id && self.matches_filter(creature_id, filter, source_controller, registry)
            }
        }
    }

    /// Collect all (power_mod, toughness_mod) from continuous effects that apply to a creature.
    fn continuous_pt_mods(&self, creature_id: ObjectId, registry: &crate::cards::CardRegistry) -> (i32, i32) {
        use crate::types::ContinuousEffect;
        let mut power = 0;
        let mut toughness = 0;
        for source in self.objects.values() {
            if source.zone != Zone::Battlefield {
                continue;
            }
            // Check instance-level effects first (e.g., Bonds of Faith).
            if let Some(ref instance_effects) = source.instance_continuous_effects {
                for effect in instance_effects {
                    if let ContinuousEffect::ModifyPT { power: p, toughness: t, scope } = effect {
                        if self.effect_applies_to(creature_id, scope, source.id, source.controller, registry) {
                            power += p;
                            toughness += t;
                        }
                    }
                }
            } else if let Some(behavior) = registry.get(source.card_id) {
                // Card-level static effects (use back face if transformed).
                let effects = if source.is_transformed {
                    behavior.back_face_data().map(|d| d.continuous_effects).unwrap_or_default()
                } else {
                    behavior.card_data().continuous_effects
                };
                for effect in &effects {
                    if let ContinuousEffect::ModifyPT { power: p, toughness: t, scope } = effect {
                        if self.effect_applies_to(creature_id, scope, source.id, source.controller, registry) {
                            power += p;
                            toughness += t;
                        }
                    }
                }
                // Dynamic P/T from auras (e.g., Wreath of Geists: +X/+X where X = creatures in graveyard).
                if source.attached_to == Some(creature_id) {
                    if let Some((p, t)) = behavior.dynamic_pt(self, source.id) {
                        power += p;
                        toughness += t;
                    }
                }
            }
        }
        (power, toughness)
    }

    /// Check if a creature has a specific continuous effect applying to it.
    pub fn has_continuous_effect(
        &self,
        creature_id: ObjectId,
        predicate: &dyn Fn(&crate::types::ContinuousEffect) -> Option<&crate::types::EffectScope>,
        registry: &crate::cards::CardRegistry,
    ) -> bool {
        for source in self.objects.values() {
            if source.zone != Zone::Battlefield {
                continue;
            }
            // Check instance-level effects first.
            if let Some(ref instance_effects) = source.instance_continuous_effects {
                for effect in instance_effects {
                    if let Some(scope) = predicate(effect) {
                        if self.effect_applies_to(creature_id, scope, source.id, source.controller, registry) {
                            return true;
                        }
                    }
                }
            } else if let Some(behavior) = registry.get(source.card_id) {
                // Use back face effects when transformed.
                let effects = if source.is_transformed {
                    behavior.back_face_data().map(|d| d.continuous_effects).unwrap_or_default()
                } else {
                    behavior.card_data().continuous_effects
                };
                for effect in &effects {
                    if let Some(scope) = predicate(effect) {
                        if self.effect_applies_to(creature_id, scope, source.id, source.controller, registry) {
                            return true;
                        }
                    }
                }
            }
        }
        false
    }

    /// Get the effective power of a creature, including continuous effects,
    /// dynamic P/T, counters, and "until end of turn" effects.
    pub fn effective_power(&self, id: ObjectId, registry: &crate::cards::CardRegistry) -> Option<i32> {
        let obj = self.get_object(id)?;

        // Check if this token has dynamic P/T tied to counter count on a source permanent
        // (e.g., Gutter Grime Ooze tokens whose P/T = slime counters on Gutter Grime).
        let mut power = if let Some(source_id) = obj.card_state.get("pt_source_counter") {
            let counter_type_val = obj.card_state.get("pt_source_counter_type")
                .map(|v| v.0).unwrap_or(0);
            let counter_type = match counter_type_val {
                1 => crate::types::CounterType::Slime,
                _ => crate::types::CounterType::PlusOnePlusOne,
            };
            self.get_object(*source_id)
                .map(|src| *src.counters.get(&counter_type).unwrap_or(&0) as i32)
                .unwrap_or(0)
        } else if let Some(behavior) = registry.get(obj.card_id) {
            // Check if this creature's own card has dynamic P/T (e.g., Geist-Honored Monk).
            if let Some((p, _)) = behavior.dynamic_pt(self, id) {
                p
            } else {
                obj.power?
            }
        } else {
            obj.power?
        };

        // Continuous effects (auras, anthems, debuffs — including dynamic aura P/T).
        let (p_mod, _) = self.continuous_pt_mods(id, registry);
        power += p_mod;

        // +1/+1 and -1/-1 counter bonuses.
        power += *obj.counters.get(&crate::types::CounterType::PlusOnePlusOne).unwrap_or(&0) as i32;
        power -= *obj.counters.get(&crate::types::CounterType::MinusOneMinusOne).unwrap_or(&0) as i32;

        // Until-end-of-turn effects.
        for effect in &self.until_end_of_turn_effects {
            if effect.target == id {
                power += effect.power_mod;
            }
        }

        Some(power)
    }

    /// Get the effective toughness of a creature.
    pub fn effective_toughness(&self, id: ObjectId, registry: &crate::cards::CardRegistry) -> Option<i32> {
        let obj = self.get_object(id)?;

        // Check if this token has dynamic P/T tied to counter count on a source permanent.
        let mut toughness = if let Some(source_id) = obj.card_state.get("pt_source_counter") {
            let counter_type_val = obj.card_state.get("pt_source_counter_type")
                .map(|v| v.0).unwrap_or(0);
            let counter_type = match counter_type_val {
                1 => crate::types::CounterType::Slime,
                _ => crate::types::CounterType::PlusOnePlusOne,
            };
            self.get_object(*source_id)
                .map(|src| *src.counters.get(&counter_type).unwrap_or(&0) as i32)
                .unwrap_or(0)
        } else if let Some(behavior) = registry.get(obj.card_id) {
            // Check if this creature's own card has dynamic P/T.
            if let Some((_, t)) = behavior.dynamic_pt(self, id) {
                t
            } else {
                obj.toughness?
            }
        } else {
            obj.toughness?
        };

        let (_, t_mod) = self.continuous_pt_mods(id, registry);
        toughness += t_mod;

        // +1/+1 and -1/-1 counter bonuses.
        toughness += *obj.counters.get(&crate::types::CounterType::PlusOnePlusOne).unwrap_or(&0) as i32;
        toughness -= *obj.counters.get(&crate::types::CounterType::MinusOneMinusOne).unwrap_or(&0) as i32;

        for effect in &self.until_end_of_turn_effects {
            if effect.target == id {
                toughness += effect.toughness_mod;
            }
        }

        Some(toughness)
    }

    /// Check if a creature is prevented from attacking (e.g., by Pacifism).
    pub fn can_attack(&self, creature_id: ObjectId, registry: &crate::cards::CardRegistry) -> bool {
        if self.has_continuous_effect(creature_id, &|e| {
            use crate::types::ContinuousEffect;
            match e {
                ContinuousEffect::PreventAttack { scope } => Some(scope),
                _ => None,
            }
        }, registry) {
            return false;
        }
        // Legacy fallback: instance_oracle_text for conditional cards (Bonds of Faith).
        for obj in self.objects.values() {
            if obj.zone == Zone::Battlefield && obj.attached_to == Some(creature_id) {
                if let Some(ref text) = obj.instance_oracle_text {
                    if text.contains("can't attack or block") {
                        return false;
                    }
                }
            }
        }
        true
    }

    /// Check if a creature is prevented from blocking.
    pub fn can_block(&self, creature_id: ObjectId, registry: &crate::cards::CardRegistry) -> bool {
        if self.has_continuous_effect(creature_id, &|e| {
            use crate::types::ContinuousEffect;
            match e {
                ContinuousEffect::PreventBlock { scope } => Some(scope),
                _ => None,
            }
        }, registry) {
            return false;
        }
        // Legacy fallback: instance_oracle_text for conditional cards (Bonds of Faith).
        for obj in self.objects.values() {
            if obj.zone == Zone::Battlefield && obj.attached_to == Some(creature_id) {
                if let Some(ref text) = obj.instance_oracle_text {
                    if text.contains("can't attack or block") {
                        return false;
                    }
                }
            }
        }
        true
    }

    /// Check if a creature on the battlefield has a given keyword ability.
    /// Checks static card keywords, continuous effect grants, aura grants, and until-EOT grants.
    pub fn has_keyword(&self, creature_id: ObjectId, keyword: crate::types::Keyword, registry: &crate::cards::CardRegistry) -> bool {
        let obj = match self.get_object(creature_id) {
            Some(o) if o.zone == Zone::Battlefield => o,
            _ => return false,
        };

        // Check if this keyword was temporarily removed until end of turn.
        if self.until_end_of_turn_removed_keywords.iter()
            .any(|r| r.target == creature_id && r.keyword == keyword) {
            return false;
        }

        // 0. Keywords stored directly on the object (tokens, or populated at creation).
        if obj.keywords.contains(&keyword) {
            return true;
        }

        // 1. Static keywords from card definition (or back face if transformed).
        if let Some(behavior) = registry.get(obj.card_id) {
            if obj.is_transformed {
                if let Some(back) = behavior.back_face_data() {
                    if back.keywords.contains(&keyword) {
                        return true;
                    }
                }
            } else if behavior.card_data().keywords.contains(&keyword) {
                return true;
            }
        }

        // 2. Keywords from continuous effects (auras with GrantKeyword, anthem keyword grants).
        let has_grant = self.has_continuous_effect(creature_id, &|e| {
            use crate::types::ContinuousEffect;
            match e {
                ContinuousEffect::GrantKeyword { keyword: kw, scope } if *kw == keyword => Some(scope),
                _ => None,
            }
        }, registry);
        if has_grant {
            return true;
        }

        // 2b. Conditional keywords (e.g., haste if opponent controls a Human).
        let has_conditional = self.has_conditional_keyword(creature_id, keyword, registry);
        if has_conditional {
            return true;
        }

        // 3. Temporary keyword grants (until end of turn).
        for grant in &self.until_end_of_turn_keywords {
            if grant.target == creature_id && grant.keyword == keyword {
                return true;
            }
        }

        false
    }

    /// Check if a creature has a conditional keyword that is currently active.
    fn has_conditional_keyword(&self, creature_id: ObjectId, keyword: crate::types::Keyword, registry: &crate::cards::CardRegistry) -> bool {
        use crate::types::{ContinuousEffect, EffectCondition};
        for source in self.objects.values() {
            if source.zone != Zone::Battlefield {
                continue;
            }
            let effects = if let Some(ref instance_effects) = source.instance_continuous_effects {
                instance_effects.clone()
            } else if let Some(behavior) = registry.get(source.card_id) {
                if source.is_transformed {
                    behavior.back_face_data().map(|d| d.continuous_effects).unwrap_or_default()
                } else {
                    behavior.card_data().continuous_effects
                }
            } else {
                continue;
            };
            for effect in &effects {
                if let ContinuousEffect::ConditionalKeyword { keyword: kw, condition, scope } = effect {
                    if *kw != keyword {
                        continue;
                    }
                    if !self.effect_applies_to(creature_id, scope, source.id, source.controller, registry) {
                        continue;
                    }
                    if self.check_condition(condition, source.id, source.controller, registry) {
                        return true;
                    }
                }
            }
        }
        false
    }

    /// Evaluate an EffectCondition for a given controller.
    fn check_condition(&self, condition: &crate::types::EffectCondition, source_id: ObjectId, controller: crate::ids::PlayerId, registry: &crate::cards::CardRegistry) -> bool {
        use crate::types::EffectCondition;
        match condition {
            EffectCondition::YouControlSubtype(subtype) => {
                self.objects.values().any(|o| {
                    o.zone == Zone::Battlefield && o.controller == controller && (
                        o.subtypes.iter().any(|s| s == subtype)
                        || registry.card_data(o.card_id)
                            .map(|d| d.subtypes.iter().any(|s| s == subtype))
                            .unwrap_or(false)
                    )
                })
            }
            EffectCondition::OpponentControlsSubtype(subtype) => {
                let opponent = self.opponent(controller);
                self.objects.values().any(|o| {
                    o.zone == Zone::Battlefield && o.controller == opponent && (
                        o.subtypes.iter().any(|s| s == subtype)
                        || registry.card_data(o.card_id)
                            .map(|d| d.subtypes.iter().any(|s| s == subtype))
                            .unwrap_or(false)
                    )
                })
            }
            EffectCondition::SelfHasKeyword(kw) => {
                // Check if the source permanent has the specified keyword.
                // Careful: don't recurse if checking indestructible conditioned on defender —
                // we check base keywords directly to avoid infinite recursion.
                self.get_object(source_id)
                    .map(|o| {
                        // Check object-level keywords.
                        if o.keywords.contains(kw) {
                            // But also check if it was temporarily removed.
                            !self.until_end_of_turn_removed_keywords.iter()
                                .any(|r| r.target == source_id && r.keyword == *kw)
                        } else {
                            // Check card_data keywords.
                            registry.card_data(o.card_id)
                                .map(|d| d.keywords.contains(kw))
                                .unwrap_or(false)
                                && !self.until_end_of_turn_removed_keywords.iter()
                                    .any(|r| r.target == source_id && r.keyword == *kw)
                        }
                    })
                    .unwrap_or(false)
            }
        }
    }

    /// Move a resolving spell to the appropriate zone.
    /// Flashback spells go to exile; others go to graveyard.
    pub fn move_spell_after_resolve(&mut self, object_id: ObjectId) {
        let exile = self.get_object(object_id)
            .map(|o| o.cast_with_flashback)
            .unwrap_or(false);
        if exile {
            self.move_object(object_id, Zone::Exile);
        } else {
            self.move_object(object_id, Zone::Graveyard);
        }
    }

    /// Add counters to a permanent.
    pub fn add_counters(&mut self, id: ObjectId, counter_type: crate::types::CounterType, count: u32) {
        if let Some(obj) = self.objects.get_mut(&id) {
            *obj.counters.entry(counter_type).or_insert(0) += count;
        }
    }

    /// Get the number of counters of a type on a permanent.
    pub fn get_counter_count(&self, id: ObjectId, counter_type: crate::types::CounterType) -> u32 {
        self.get_object(id)
            .and_then(|o| o.counters.get(&counter_type))
            .copied()
            .unwrap_or(0)
    }

    /// Is the game over?
    pub fn is_game_over(&self) -> bool {
        self.result.is_some()
    }
}


/// A single game object — an instance of a card on the battlefield, in hand, etc.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GameObject {
    pub id: ObjectId,
    pub card_id: CardId,
    pub name: String,
    pub owner: PlayerId,
    pub controller: PlayerId,
    pub zone: Zone,

    // Battlefield state
    pub tapped: bool,
    pub summoning_sick: bool,
    pub damage_marked: u32,
    /// Which creatures have dealt damage to this creature this turn.
    /// Used by Abattoir Ghoul ("when creature dealt damage by this dies").
    #[serde(default)]
    pub damaged_by: Vec<ObjectId>,
    /// Whether this creature has been dealt damage by a source with deathtouch.
    pub dealt_deathtouch_damage: bool,

    // Characteristics (from card data, may be modified by effects later)
    pub power: Option<i32>,
    pub toughness: Option<i32>,
    pub colors: Vec<crate::types::Color>,
    /// Keywords on this object (populated from card_data for real cards, set directly for tokens).
    pub keywords: Vec<crate::types::Keyword>,
    /// Card types on this object (populated from card_data, set directly for tokens).
    pub card_types: Vec<crate::types::CardType>,
    /// Subtypes on this object (for tokens — regular cards use CardData.subtypes via registry).
    #[serde(default)]
    pub subtypes: Vec<String>,

    // Targets chosen when this spell was cast (only relevant while on the stack).
    pub targets: Vec<crate::actions::Target>,

    // Aura/equipment: what this is attached to.
    pub attached_to: Option<ObjectId>,
    // Curse aura: attached to a player (instead of an object).
    pub attached_to_player: Option<PlayerId>,

    // Tracks zone changes for staleness detection (XMage pattern).
    pub zone_change_count: u32,

    /// Whether this object is a token (tokens cease to exist when not on the battlefield).
    pub is_token: bool,
    /// Whether this permanent is legendary (for the legend rule SBA).
    #[serde(default)]
    pub is_legendary: bool,

    /// Whether this spell was cast using flashback (exiled instead of going to graveyard).
    #[serde(default)]
    pub cast_with_flashback: bool,

    /// Per-instance oracle text override (e.g., Bonds of Faith conditional effect).
    /// When set, aura parsing uses this instead of the card's static oracle text.
    #[serde(default)]
    pub instance_oracle_text: Option<String>,

    /// Per-instance continuous effects that override the card's static effects.
    /// Set by on_enter_battlefield for conditional cards (e.g., Bonds of Faith).
    #[serde(default)]
    pub instance_continuous_effects: Option<Vec<crate::types::ContinuousEffect>>,

    /// Card-specific persistent state (e.g., Fiend Hunter stores the exiled creature ID).
    /// Keyed by purpose string, value is an ObjectId.
    #[serde(default)]
    pub card_state: HashMap<String, ObjectId>,

    /// Counters on this permanent (+1/+1, -1/-1, etc.).
    pub counters: HashMap<crate::types::CounterType, u32>,

    /// Number of regeneration shields (consumed instead of destruction).
    #[serde(default)]
    pub regeneration_shields: u32,

    /// Whether this permanent is equipment (stays on battlefield when unattached).
    #[serde(default)]
    pub is_equipment: bool,

    /// Whether this double-faced card is on its back face.
    #[serde(default)]
    pub is_transformed: bool,

    /// Chosen X value for X-cost spells (stored while on the stack).
    #[serde(default)]
    pub x_value: Option<u32>,

    /// Activated abilities used this turn (for once-per-turn tracking).
    #[serde(default)]
    pub abilities_activated_this_turn: std::collections::HashSet<usize>,
}

/// A player's state.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlayerState {
    pub id: PlayerId,
    pub life: i32,
    pub mana_pool: ManaPool,
    pub land_plays_remaining: u32,
    pub lost: bool,
    pub has_drawn_from_empty: bool,
    /// Order of cards in library (first element is top of library).
    pub library_order: Vec<ObjectId>,
}

impl PlayerState {
    pub fn new(id: PlayerId) -> Self {
        Self {
            id,
            life: 40, // commander starting life
            mana_pool: ManaPool::new(),
            land_plays_remaining: 1,
            lost: false,
            has_drawn_from_empty: false,
            library_order: Vec::new(),
        }
    }

    /// Draw the top card of the library. Returns None if library is empty.
    pub fn draw_top_card(&mut self) -> Option<ObjectId> {
        if self.library_order.is_empty() {
            self.has_drawn_from_empty = true;
            None
        } else {
            Some(self.library_order.remove(0))
        }
    }
}

/// Combat state, tracking attackers and blockers.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CombatState {
    /// Map of attacker ObjectId -> defending PlayerId.
    pub attackers: HashMap<ObjectId, PlayerId>,
    /// Map of attacker ObjectId -> list of blockers assigned to it.
    pub blocker_assignments: HashMap<ObjectId, Vec<ObjectId>>,
}

impl CombatState {
    pub fn new() -> Self {
        Self {
            attackers: HashMap::new(),
            blocker_assignments: HashMap::new(),
        }
    }
}

/// What the engine is waiting for the player to do.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum AwaitingAction {
    DeclareAttackers,
    DeclareBlockers { defending_player: PlayerId },
    DiscardToHandSize { player: PlayerId, discard_count: usize },
    /// A card or trigger needs a player to make a choice during resolution.
    ResolutionChoice {
        player: PlayerId,
        source: ObjectId,
        choice: ResolutionChoiceKind,
    },
}

/// Describes what kind of mid-resolution choice is needed.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ResolutionChoiceKind {
    /// Choose whether to pay a cost (Frightful Delusion's "pay {1}").
    PayOrNot {
        description: String,
        spell_id: ObjectId,
        source_spell_id: ObjectId,
    },
    /// Choose one target from a list (damage, destroy, return, counters).
    ChooseTarget {
        description: String,
        options: Vec<crate::actions::Target>,
        optional: bool,
        effect: PendingEffect,
    },
    /// A yes/no choice ("you may" abilities).
    /// If yes, the card's trigger continues with its effect.
    /// If no, nothing happens.
    YesNo {
        description: String,
        source_card: ObjectId,
    },
    /// Choose a card from hand to discard (Murder of Crows, future discard effects).
    ChooseCardFromHand {
        description: String,
        player: PlayerId,
        cards: Vec<ObjectId>,
    },
    /// Choose one card from a revealed set to keep (Forbidden Alchemy).
    ChooseFromRevealed {
        description: String,
        revealed: Vec<ObjectId>,
        spell_id: ObjectId,
    },
}

/// What happens to the chosen target when a ResolutionChoice is resolved.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum PendingEffect {
    /// Deal N damage to the chosen target.
    DealDamage { amount: u32, source_id: ObjectId, source_name: String },
    /// Destroy the chosen permanent.
    Destroy { source_name: String },
    /// Move chosen creature from graveyard to battlefield.
    ReturnToBattlefield { spell_id: ObjectId },
    /// Put +1/+1 counters on chosen creature.
    AddCounters { count: u32, human_bonus: bool },
    /// Apply -N/-M until end of turn to the chosen creature.
    DebuffUntilEOT { power: i32, toughness: i32, source_name: String },
    /// Target creature can't block this turn.
    CantBlockThisTurn { source_name: String },
    /// Target player mills N cards.
    Mill { count: u32, source_name: String },
    /// Exile the chosen creature and store its ID on the source permanent.
    ExileAndStore { source_id: ObjectId, source_name: String },
    /// Target player draws a card and loses 1 life (Bloodgift Demon).
    DrawAndLoseLife { source_name: String },
    /// Destroy target creature matching a filter (Reaper from the Abyss).
    DestroyCreature { source_name: String },
    /// Exile the chosen card from graveyard (Curse of Oblivion).
    /// If remaining > 0, presents another exile choice after this one.
    ExileCurseOfOblivion { remaining: u32 },
    /// Return the chosen object to its owner's hand.
    ReturnToHand { source_name: String },
    /// Put the chosen object on top of its owner's library.
    PutOnTopOfLibrary { source_name: String },
    /// Sacrifice the chosen creature and gain life equal to its toughness (Tribute to Hunger).
    /// `beneficiary` gains the life; `spell_id` is cleaned up after resolution.
    SacrificeAndGainLife { beneficiary: PlayerId, spell_id: ObjectId },
}

/// Game result.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum GameResult {
    Winner(PlayerId),
    Draw,
}

/// Day/night state for werewolf transform tracking.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum DayNight {
    Day,
    Night,
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ids::CardId;

    #[test]
    fn create_and_move_object() {
        let mut state = GameState::new(2);
        let id = state.create_object(CardId(1), PlayerId(0), Zone::Hand, None, None);

        assert_eq!(state.get_object(id).unwrap().zone, Zone::Hand);

        state.move_object(id, Zone::Battlefield);
        let obj = state.get_object(id).unwrap();
        assert_eq!(obj.zone, Zone::Battlefield);
        assert!(obj.summoning_sick);
        assert_eq!(obj.zone_change_count, 1);
    }

    #[test]
    fn objects_in_zone_filters_correctly() {
        let mut state = GameState::new(2);
        let p0 = PlayerId(0);
        let p1 = PlayerId(1);

        state.create_object(CardId(1), p0, Zone::Hand, None, None);
        state.create_object(CardId(2), p0, Zone::Hand, None, None);
        state.create_object(CardId(1), p1, Zone::Hand, None, None);

        assert_eq!(state.objects_in_zone(Zone::Hand, p0).len(), 2);
        assert_eq!(state.objects_in_zone(Zone::Hand, p1).len(), 1);
    }

    #[test]
    fn leaving_battlefield_resets_state() {
        let mut state = GameState::new(2);
        let id = state.create_object(CardId(1), PlayerId(0), Zone::Battlefield, Some(2), Some(2));

        {
            let obj = state.get_object_mut(id).unwrap();
            obj.tapped = true;
            obj.damage_marked = 1;
        }

        state.move_object(id, Zone::Graveyard);
        let obj = state.get_object(id).unwrap();
        assert!(!obj.tapped);
        assert_eq!(obj.damage_marked, 0);
        assert!(!obj.summoning_sick);
    }

    #[test]
    fn draw_from_empty_library() {
        let mut state = GameState::new(2);
        let player = state.get_player_mut(PlayerId(0));
        assert!(player.draw_top_card().is_none());
        assert!(player.has_drawn_from_empty);
    }
}
