#!/usr/bin/env python3
"""Generate the coverage deck set: ten two-color decks that together contain
every castable card the engine implements, exactly once each.

Input: a TSV of the registry (CARD\tname\tcost\tcolors\ttypes\tsubtypes\tsuper),
produced by dumping CardRegistry::with_all_cards() — see the coverage test in
mtg-engine/tests/deck_coverage.rs for how the two are kept in sync.

Layout: one deck per color pair (WU, WB, WR, WG, UB, UR, UG, BR, BG, RG).
Each color's cards are dealt round-robin by mana value into the four decks
that play that color, so every deck gets a spread of the curve rather than a
random clump. Gold cards go to their exact pair, artifacts are dealt across
all ten, and each deck gets its on-color dual land plus a basic-land mana
base sized to its spell count.

Usage: scripts/make_coverage_decks.py /tmp/cards.tsv decks/coverage
"""
import re
import sys
from pathlib import Path

PAIRS = ["WU", "WB", "WR", "WG", "UB", "UR", "UG", "BR", "BG", "RG"]
BASIC = {"W": "Plains", "U": "Island", "B": "Swamp", "R": "Mountain", "G": "Forest"}
DUALS = {
    "WU": "Moorland Haunt", "WB": "Isolated Chapel", "WR": "Clifftop Retreat",
    "WG": "Gavony Township", "UB": "Nephalia Drownyard", "UR": "Sulfur Falls",
    "UG": "Hinterland Harbor", "BR": "Stensia Bloodhall", "BG": "Woodland Cemetery",
    "RG": "Kessig Wolf Run",
}
# Colorless utility lands, one per deck until they run out.
UTILITY_LANDS = ["Ghost Quarter", "Shimmering Grotto"]


def mana_value(cost: str) -> int:
    total = 0
    for sym in re.findall(r"\{([^}]+)\}", cost):
        if sym.isdigit():
            total += int(sym)
        elif sym != "X":
            total += 1
    return total


def main() -> None:
    tsv, outdir = sys.argv[1], Path(sys.argv[2])
    outdir.mkdir(parents=True, exist_ok=True)

    mono: dict[str, list[tuple[int, str]]] = {c: [] for c in "WUBRG"}
    artifacts: list[tuple[int, str]] = []
    gold: dict[str, list[str]] = {}
    for line in open(tsv):
        parts = line.rstrip("\n").split("\t")
        _, name, cost, colors, types = parts[:5]
        if "Land" in types:
            continue
        mv = mana_value(cost)
        if len(colors) == 1:
            mono[colors].append((mv, name))
        elif len(colors) == 2:
            key = min(p for p in PAIRS if set(p) == set(colors))
            gold.setdefault(key, []).append(name)
        else:
            artifacts.append((mv, name))

    decks: dict[str, list[str]] = {p: [] for p in PAIRS}

    # Deal each color's cards round-robin by mana value into its four decks.
    for color, cards in mono.items():
        homes = [p for p in PAIRS if color in p]
        for i, (_, name) in enumerate(sorted(cards)):
            decks[homes[i % len(homes)]].append(name)

    for pair, names in gold.items():
        decks[pair].extend(names)

    for i, (_, name) in enumerate(sorted(artifacts)):
        decks[PAIRS[i % len(PAIRS)]].append(name)

    utility = list(UTILITY_LANDS)
    for pair in PAIRS:
        spells = decks[pair]
        # ~40% lands: dual + optional utility land + basics split evenly.
        lands = max(15, round(len(spells) * 2 / 3))
        nonbasic = [DUALS[pair]] + ([utility.pop(0)] if utility else [])
        n_basic = lands - len(nonbasic)
        first, second = pair[0], pair[1]
        counts = {BASIC[first]: (n_basic + 1) // 2, BASIC[second]: n_basic // 2}

        path = outdir / f"{pair.lower()}-coverage.txt"
        with open(path, "w") as f:
            f.write(f"# Coverage deck {pair}: every card once; generated by\n")
            f.write("# scripts/make_coverage_decks.py, coverage pinned by\n")
            f.write("# mtg-engine/tests/deck_coverage.rs.\n\n")
            for land, n in counts.items():
                f.write(f"{n} {land}\n")
            for land in nonbasic:
                f.write(f"1 {land}\n")
            f.write("\n")
            for name in sorted(spells):
                f.write(f"1 {name}\n")
        print(f"{path}: {len(spells)} spells + {lands} lands")


if __name__ == "__main__":
    main()
